<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { Plus, Copy, Save, Check, RefreshCw } from 'lucide-vue-next';
import type { AgentConfig, ConfigWrite, ModelConfig } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue'; import EmptyState from '@ui/EmptyState.vue'; import Modal from '@ui/Modal.vue';
import { request, errorText, clone, notify, allPages, useDirty } from '../lib';
const configs = ref<AgentConfig[]>([]); const models = ref<ModelConfig[]>([]); const selectedId = ref(''); const loading = ref(false); const loaded = ref(false); const error = ref(''); const busy = ref(''); const publishOpen = ref(false);
const selected = computed(() => configs.value.find(config => config.id === selectedId.value)); const published = computed(() => configs.value.find(config => config.status === 'published')); const readonly = computed(() => selected.value?.status === 'published');
const blank = (): ConfigWrite => ({ name: '', modelId: '', summaryModelId: '', maxModelCalls: 20, maxToolCalls: 40, maxSeconds: 180, summaryTokens: 12000, summaryMessages: 30, summaryRatio: 0.7, subagentConcurrency: 2, tools: ['list_dir', 'read_file', 'search_content', 'write_file', 'bash', 'web_search', 'delegate_research'], systemPrompt: '' });
const form = ref<ConfigWrite>(blank()); const baseline = ref(JSON.stringify(form.value)); const editing = ref(false); const dirty = computed(() => editing.value && !readonly.value && JSON.stringify(form.value) !== baseline.value); const confirmDiscard = useDirty(dirty);
const availableModels = computed(() => models.value.filter(model => model.enabled && model.verified));
const tools: { id: ConfigWrite['tools'][number]; label: string }[] = [{ id: 'list_dir', label: '浏览目录' }, { id: 'read_file', label: '读取文件' }, { id: 'search_content', label: '检索内容' }, { id: 'write_file', label: '写入工作文件' }, { id: 'bash', label: '隔离命令执行' }, { id: 'web_search', label: '网页检索' }, { id: 'delegate_research', label: '委派研究子任务' }];
const fields: { key: 'maxModelCalls' | 'maxToolCalls' | 'maxSeconds' | 'summaryTokens' | 'summaryMessages' | 'summaryRatio' | 'subagentConcurrency'; label: string; min: number; max?: number; step: number }[] = [
  { key: 'maxModelCalls', label: '模型调用上限', min: 1, max: 100, step: 1 }, { key: 'maxToolCalls', label: '工具调用上限', min: 1, max: 200, step: 1 }, { key: 'maxSeconds', label: '总时限（秒）', min: 10, max: 1800, step: 1 }, { key: 'subagentConcurrency', label: '子任务并发上限', min: 0, max: 8, step: 1 }, { key: 'summaryTokens', label: '摘要触发 Token', min: 1000, step: 1 }, { key: 'summaryMessages', label: '摘要触发消息数', min: 4, step: 1 }, { key: 'summaryRatio', label: '摘要触发窗口比例', min: 0.01, max: 1, step: 0.01 },
];
function writeOf(config: AgentConfig): ConfigWrite { const { id, version, status, ...write } = clone(config); return write; }
function select(config: AgentConfig) { if (!confirmDiscard()) return; selectedId.value = config.id; form.value = writeOf(config); baseline.value = JSON.stringify(form.value); editing.value = true; error.value = ''; }
function create(copy = false) { if (!confirmDiscard()) return; form.value = copy && selected.value ? { ...writeOf(selected.value), name: `${selected.value.name} 副本` } : blank(); selectedId.value = ''; baseline.value = JSON.stringify(blank()); editing.value = true; error.value = ''; }
const diff = computed(() => { if (!published.value) return '还没有已发布版本。'; const previous = writeOf(published.value); return (Object.keys(form.value) as (keyof ConfigWrite)[]).filter(key => JSON.stringify(form.value[key]) !== JSON.stringify(previous[key])).map(key => `${key}\n  当前发布：${JSON.stringify(previous[key])}\n  当前草稿：${JSON.stringify(form.value[key])}`).join('\n\n') || '与已发布配置内容相同。'; });
async function load() { if (loading.value || (dirty.value && !confirmDiscard())) return; loading.value = true; error.value = ''; try { const [nextConfigs, nextModels] = await Promise.all([allPages<AgentConfig>('listConfigs'), allPages<ModelConfig>('listModels')]); configs.value = nextConfigs; models.value = nextModels; loaded.value = true; const next = nextConfigs.find(config => config.id === selectedId.value) || nextConfigs[0]; if (next) { selectedId.value = next.id; form.value = writeOf(next); baseline.value = JSON.stringify(form.value); editing.value = true; } } catch (err) { error.value = errorText(err); } finally { loading.value = false; } }
async function save() { if (busy.value || readonly.value) return; busy.value = 'save'; error.value = ''; try { const config = await request<AgentConfig>(selectedId.value ? 'saveConfig' : 'createConfig', { path: selectedId.value ? { id: selectedId.value } : undefined, body: form.value }); configs.value = [config, ...configs.value.filter(item => item.id !== config.id)]; selectedId.value = config.id; form.value = writeOf(config); baseline.value = JSON.stringify(form.value); notify('配置草稿已保存。发布后对后续运行生效。'); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
async function publish() { if (!selected.value || dirty.value || busy.value) return; busy.value = 'publish'; error.value = ''; try { const config = await request<AgentConfig>('publishConfig', { path: { id: selected.value.id } }); configs.value = [config, ...configs.value.filter(item => item.id !== config.id)]; publishOpen.value = false; notify(`配置 ${config.version} 已发布，后续新运行将使用该版本。`); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
onMounted(load);
</script>
<template><header class="page-header"><div><div class="eyebrow">AGENT CONFIGURATION</div><h1>把工作方式，写进配置</h1><p>管理模型、工具和预算，按版本发布 Agent 行为。</p></div><div class="actions"><button class="button" :disabled="loading || !!busy" @click="load"><RefreshCw :size="16" />刷新</button><button class="button button--primary" :disabled="!!busy" @click="create()"><Plus :size="16" />新建草稿</button></div></header>
  <p v-if="error && !publishOpen" class="alert alert--danger" role="alert">{{ error }}</p><div v-if="loading && !loaded" class="skeleton" role="status" aria-label="加载配置"></div>
  <div v-else class="admin-config-layout"><aside class="admin-config-list" aria-label="配置版本"><button v-for="config in configs" :key="config.id" class="button admin-config-choice" :aria-pressed="selectedId === config.id" :disabled="!!busy" @click="select(config)"><span>{{ config.name }}<small>{{ config.version }}</small></span><Badge :status="config.status" /></button><p v-if="!configs.length" class="meta">暂无配置版本。</p></aside>
    <EmptyState v-if="!editing" title="创建首个 Agent 配置" description="选择已验证模型，设置工具和预算后保存草稿。"><button class="button button--primary" @click="create()">新建配置</button></EmptyState>
    <form v-else class="card admin-form" @submit.prevent="save"><div class="section-heading"><div><h2>{{ selected ? `${selected.name} · ${selected.version}` : '新配置草稿' }}</h2><Badge v-if="selected" :status="selected.status" /></div><button v-if="selected" class="button" type="button" :disabled="!!busy" @click="create(true)"><Copy :size="16" />复制为草稿</button></div><p v-if="readonly" class="alert alert--info">已发布配置保持不可变。需要调整时请复制为新草稿。</p><p v-if="dirty" class="meta" role="status">有未保存的修改</p>
      <fieldset class="admin-fieldset" :disabled="readonly || !!busy"><div class="stack"><label class="field">配置名称<input v-model="form.name" class="field-control" required maxlength="120"></label><div class="form-grid"><label class="field">主模型<select v-model="form.modelId" class="field-control" required><option value="" disabled>选择已验证模型</option><option v-if="form.modelId && !availableModels.some(model => model.id === form.modelId)" :value="form.modelId">{{ models.find(model => model.id === form.modelId)?.name || form.modelId }}（不可用）</option><option v-for="model in availableModels" :key="model.id" :value="model.id">{{ model.name }} · {{ model.role }}</option></select></label><label class="field">摘要模型<select v-model="form.summaryModelId" class="field-control" required><option value="" disabled>选择已验证模型</option><option v-if="form.summaryModelId && !availableModels.some(model => model.id === form.summaryModelId)" :value="form.summaryModelId">{{ models.find(model => model.id === form.summaryModelId)?.name || form.summaryModelId }}（不可用）</option><option v-for="model in availableModels" :key="model.id" :value="model.id">{{ model.name }} · {{ model.role }}</option></select></label></div><p v-if="!availableModels.length" class="alert">暂无已启用并验证的模型，请先在<RouterLink to="/models">模型与连接</RouterLink>中完成配置。</p>
      <div><h3>运行预算</h3><div class="form-grid"><label v-for="field in fields" :key="field.key" class="field">{{ field.label }}<input v-model.number="form[field.key]" class="field-control" type="number" :min="field.min" :max="field.max" :step="field.step" required></label></div></div><div><h3>可用工具</h3><div class="admin-checks"><label v-for="tool in tools" :key="tool.id"><input v-model="form.tools" type="checkbox" :value="tool.id">{{ tool.label }}<span class="meta mono">{{ tool.id }}</span></label></div></div><label class="field">系统提示词<textarea v-model="form.systemPrompt" class="field-control" rows="10" required maxlength="32000" placeholder="说明如何理解偏好、核验来源、组织简报与处理缺失证据。"></textarea><span class="meta">{{ form.systemPrompt.length }} / 32000</span></label></div></fieldset>
      <details v-if="!readonly" class="admin-diff admin-section"><summary>与当前发布版本的差异</summary><pre>{{ diff }}</pre></details><div v-if="!readonly" class="actions admin-form-actions"><button class="button button--primary" type="submit" :disabled="!!busy || (!!selected && !dirty)"><Save :size="16" />{{ busy === 'save' ? '保存中…' : '保存草稿' }}</button><button v-if="selected" class="button" type="button" :disabled="!!busy || dirty" @click="publishOpen = true"><Check :size="16" />发布版本</button><span v-if="dirty && selected" class="meta">发布前需保存修改。</span></div>
    </form>
  </div>
  <Modal :open="publishOpen" title="发布 Agent 配置" @close="!busy && (publishOpen = false)"><p>发布 {{ selected?.name }}（{{ selected?.version }}）后，新运行将使用该配置。已经开始的运行继续使用其配置快照。</p><p v-if="error" class="alert alert--danger" role="alert">{{ error }}</p><template #footer><button class="button" :disabled="!!busy" @click="publishOpen = false">返回检查</button><button class="button button--primary" :disabled="!!busy" @click="publish">{{ busy ? '发布中…' : '发布配置' }}</button></template></Modal>
</template>
