<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { RefreshCw } from 'lucide-vue-next';
import type { Delivery } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue'; import EmptyState from '@ui/EmptyState.vue';
import { request, errorText, formatDate, useCollection, intentKeys, useRefresh, notify } from '../lib';
const collection = useCollection<Delivery>('listAdminDeliveries'); const { items, loading, loaded, error: loadError, nextCursor, scope } = collection;
const filter = ref('all'); const search = ref(''); const busy = ref(''); const error = ref(''); const keys = intentKeys();
const deliveries = computed(() => items.value.filter(item => (filter.value === 'all' || item.status === filter.value) && `${item.userName} ${item.briefId} ${item.id}`.toLowerCase().includes(search.value.trim().toLowerCase())));
async function retry(item: Delivery) { if (busy.value) return; busy.value = item.id; error.value = ''; try { const updated = await request<Delivery>('retryAdminDelivery', { path: { id: item.id }, idempotencyKey: keys.get(item.id) }); collection.replace(updated); keys.done(item.id); notify('补发请求已排队，继续使用同一份简报。实际发布结果稍后更新。'); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
onMounted(() => collection.load());
useRefresh(() => { if (!busy.value && items.value.some(item => item.status === 'pending')) return collection.load(); }, 10000);
</script>
<template><header class="page-header"><div><div class="eyebrow">DELIVERY OPERATIONS</div><h1>投递记录</h1><p>分别查看简报生成与站内通知状态。</p></div><button class="button" :disabled="loading" @click="collection.load()"><RefreshCw :size="16" />刷新记录</button></header><p class="alert alert--info">“已发布”表示简报在站内可见，不代表用户已读。失败补发沿用原简报内容。</p><p v-if="error || loadError" class="alert alert--danger" role="alert">{{ error || loadError }}</p><div class="admin-toolbar"><label class="field">用户或简报 ID<input v-model="search" class="field-control" type="search" placeholder="筛选已加载记录"></label><label class="field">投递状态<select v-model="filter" class="field-control"><option value="all">全部状态</option><option value="failed">失败</option><option value="unknown">状态未知</option><option value="pending">待发布</option><option value="submitted">已发布</option></select></label></div><div v-if="loading && !loaded" class="skeleton" role="status" aria-label="加载投递记录"></div><EmptyState v-else-if="!deliveries.length" title="没有匹配的投递记录" :description="loadError || '站内通知创建后会显示在这里，也可调整筛选条件。'"><button v-if="loadError" class="button" @click="collection.load()">重试</button></EmptyState><div v-else class="table-wrap" tabindex="0" role="region" aria-label="投递记录，可横向滚动"><table class="data-table admin-table"><thead><tr><th>用户 / 目的地</th><th>简报</th><th>状态</th><th>最近尝试</th><th>结果与操作</th></tr></thead><tbody><tr v-for="item in deliveries" :key="item.id"><td class="wide-cell"><strong>{{ item.userName }}</strong><small>{{ item.destination }}</small><small>站内通知</small></td><td class="wide-cell mono">{{ item.briefId }}</td><td><Badge :status="item.status" /></td><td class="nowrap">{{ formatDate(item.time) }}<small>已尝试 {{ item.attempts }} 次</small></td><td class="wide-cell"><p class="meta">{{ item.error || (item.status === 'submitted' ? '站内通知已发布。' : item.status === 'unknown' ? '尚未确认发布结果。' : '等待后台发布结果。') }}</p><button v-if="item.status === 'failed'" class="button" :disabled="!!busy" @click="retry(item)"><RefreshCw :size="15" />{{ busy === item.id ? '正在提交…' : '补发站内通知' }}</button><span v-if="item.status === 'unknown'" class="meta">确认发布状态后再补发，避免重复通知。</span></td></tr></tbody></table></div><div class="admin-pagination"><span class="meta">{{ scope }} · 筛选应用于已加载记录</span><button v-if="nextCursor" class="button" :disabled="loading" @click="collection.load(true)">加载更多</button></div></template>
