<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, Plus, Play, RefreshCw } from 'lucide-vue-next';
import type { Evaluation, EvalCase, EvalCaseWrite, AcceptedEvaluation, EvaluationScore, Preferences } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue'; import Modal from '@ui/Modal.vue'; import EmptyState from '@ui/EmptyState.vue';
import { request, errorText, formatDate, number, allPages, useCollection, useDirty, useRefresh, intentKeys, notify } from '../lib';
const route = useRoute(); const router = useRouter(); const collection = useCollection<Evaluation>('listEvaluations'); const { items, loading, loaded, error: loadError, nextCursor, scope } = collection;
const cases = ref<EvalCase[]>([]); const referencesLoaded = ref(false); const referencesLoading = ref(false); const referenceError = ref('');
const tab = ref('experiments'); const busy = ref(''); const error = ref(''); const selected = ref<Evaluation | null>(null); const detailLoading = ref(false); const detailError = ref('');
const firstId = ref(''); const secondId = ref(''); const first = computed(() => items.value.find(item => item.id === firstId.value)); const second = computed(() => items.value.find(item => item.id === secondId.value));
const comparable = computed(() => !!first.value && !!second.value && firstId.value !== secondId.value && first.value.datasetVersion === second.value.datasetVersion && first.value.scorerVersion === second.value.scorerVersion);
const metrics = [ { key: 'relevance', label: '偏好相关性', unit: '/ 5', source: '模型评分', digits: 1 }, { key: 'faithfulness', label: '事实忠实度', unit: '/ 5', source: '模型评分', digits: 1 }, { key: 'citations', label: '引用完整率', unit: '%', source: '规则检查', digits: 1 }, { key: 'cost', label: '总费用', unit: 'USD', source: '用量汇总', digits: 4 }, { key: 'latency', label: '平均耗时', unit: '秒', source: '执行计时', digits: 1 } ] as const;
type Metric = typeof metrics[number]['key'];
function value(item: Evaluation | undefined | null, key: Metric) { return number(item?.[key], metrics.find(metric => metric.key === key)?.digits || 0); }
function delta(key: Metric) { if (!comparable.value) return '输入或评分版本不同'; const a = first.value?.[key]; const b = second.value?.[key]; if (a == null || b == null) return '尚无可比较结果'; const difference = b - a; return `${difference > 0 ? '+' : ''}${number(difference, metrics.find(metric => metric.key === key)?.digits || 0)}`; }
const metricLabel: Record<EvaluationScore['metric'], string> = { relevance: '偏好相关性', faithfulness: '事实忠实度', freshness: '新鲜度', deduplication: '去重', sourceCoverage: '来源覆盖', citationAccuracy: '引用准确性', latency: '耗时', cost: '费用' };
const methodLabel = { rule: '规则检查', human: '人工评分', llm: '模型评分' };
const editing = ref(false); const editId = ref(''); const form = ref({ name: '', preference: '', expected: '' }); const fixedAt = ref(''); const snapshotMode = ref<'capture' | 'explicit'>('capture'); const snapshotText = ref(''); const preferencesText = ref(''); const formError = ref(''); const baseline = ref('');
const formSnapshot = () => JSON.stringify([form.value, fixedAt.value, snapshotMode.value, snapshotText.value, preferencesText.value]);
const dirty = computed(() => editing.value && formSnapshot() !== baseline.value); const confirmDiscard = useDirty(dirty); const keys = intentKeys();
function edit(item?: EvalCase) { editId.value = item?.id || ''; form.value = item ? { name: item.name, preference: item.preference, expected: item.expected } : { name: '', preference: '', expected: '' }; fixedAt.value = item?.fixedAt || ''; snapshotMode.value = item ? 'explicit' : 'capture'; snapshotText.value = item?.sourceSnapshotIds.join('\n') || ''; preferencesText.value = item ? JSON.stringify(item.preferenceSnapshot, null, 2) : ''; baseline.value = formSnapshot(); formError.value = ''; editing.value = true; }
function close() { if (!busy.value && confirmDiscard()) editing.value = false; }
async function save() { if (busy.value) return; formError.value = ''; let body: EvalCaseWrite;
  try { body = { ...form.value }; if (fixedAt.value.trim()) { const date = new Date(fixedAt.value.trim()); if (!Number.isFinite(date.getTime())) throw new Error('固定时钟需为有效的 ISO 时间，例如 2026-09-19T00:00:00Z。'); body.fixedAt = date.toISOString(); } if (snapshotMode.value === 'explicit') body.sourceSnapshotIds = [...new Set(snapshotText.value.split(/[\n,]/).map(item => item.trim()).filter(Boolean))]; if (preferencesText.value.trim()) body.preferenceSnapshot = JSON.parse(preferencesText.value) as Preferences; }
  catch (err) { formError.value = errorText(err); return; }
  busy.value = 'case'; try { const item = await request<EvalCase>(editId.value ? 'saveEvalCase' : 'createEvalCase', { path: editId.value ? { id: editId.value } : undefined, body }); cases.value = [item, ...cases.value.filter(previous => previous.id !== item.id)]; editing.value = false; notify(`固定样例已保存，修订 ${item.revision}；已创建实验保持原输入。`); } catch (err) { formError.value = errorText(err); } finally { busy.value = ''; }
}
async function loadReferences() { if (referencesLoading.value) return; referencesLoading.value = true; referenceError.value = ''; try { cases.value = await allPages<EvalCase>('listEvalCases'); referencesLoaded.value = true; } catch (err) { referenceError.value = errorText(err); } finally { referencesLoading.value = false; } }
async function run() { if (busy.value || !referencesLoaded.value || !cases.value.length) return; busy.value = 'run'; error.value = ''; const intent = 'run-evaluation'; try { const accepted = await request<AcceptedEvaluation>('runEvaluation', { body: {}, idempotencyKey: keys.get(intent) }); keys.done(intent); notify('评估实验已排队，输入与当前部署配置已固定。'); await router.push(`/evaluations/${accepted.evaluationId}`); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
let revision = 0;
async function loadDetail() { const id = String(route.params.id || ''); if (!id) return; const current = revision; detailLoading.value = true; detailError.value = ''; try { const item = await request<Evaluation>('getEvaluation', { path: { id } }); if (current === revision) { selected.value = item; collection.replace(item); } } catch (err) { if (current === revision) detailError.value = errorText(err); } finally { if (current === revision) detailLoading.value = false; } }
watch(() => route.params.id, () => { revision++; selected.value = null; detailError.value = ''; if (route.params.id) void loadDetail(); }, { immediate: true });
watch(items, values => { if (!firstId.value) firstId.value = values[0]?.id || ''; if (!secondId.value) secondId.value = values[1]?.id || ''; });
onMounted(() => { void collection.load(); void loadReferences(); });
useRefresh(() => { if (selected.value && ['running', 'queued'].includes(selected.value.status) && !detailLoading.value) return loadDetail(); }, 5000);
</script>
<template><template v-if="route.params.id"><RouterLink class="admin-back" to="/evaluations"><ArrowLeft :size="16" />全部评估实验</RouterLink><div v-if="detailLoading && !selected" class="skeleton" role="status" aria-label="加载评估结果"></div><EmptyState v-else-if="!selected" title="无法加载这个实验" :description="detailError || '实验不存在或已不可访问。'" error><button class="button" @click="loadDetail">重试</button></EmptyState>
  <template v-if="selected"><header class="page-header"><div><div class="eyebrow">EVALUATION DETAIL</div><h1>{{ selected.name }}</h1><p>{{ selected.configVersion }} · {{ selected.cases }} 个固定样例 · {{ formatDate(selected.createdAt) }}</p></div><div class="actions"><Badge :status="selected.status" /><button class="button" :disabled="detailLoading" @click="loadDetail"><RefreshCw :size="16" />刷新</button></div></header><p v-if="detailError" class="alert alert--danger" role="alert">{{ detailError }} 已保留上次结果。</p><p v-if="['queued','running'].includes(selected.status)" class="alert alert--info" role="status">评估正在{{ selected.status === 'queued' ? '排队' : '运行' }}。评分未返回时显示“—”。</p><p v-if="selected.status === 'failed'" class="alert alert--danger">实验执行失败。已经产生的结果保留，具体原因见逐项评分。</p>
    <div class="metric-grid"><div v-for="metric in metrics.slice(0,4)" :key="metric.key" class="metric"><span class="meta">{{ metric.label }}</span><strong>{{ value(selected, metric.key) }} <small>{{ metric.unit }}</small></strong><span class="meta">{{ metric.source }}</span></div></div>
    <section class="card"><h2>评分来源与固定输入</h2><dl class="admin-kv"><dt>实验配置</dt><dd>{{ selected.configVersion }}</dd><dt>模型 ID</dt><dd class="mono">{{ selected.modelId }}</dd><dt>数据集版本</dt><dd class="mono">{{ selected.datasetVersion }}</dd><dt>评分器版本</dt><dd class="mono">{{ selected.scorerVersion }}</dd><dt>平均耗时</dt><dd>{{ value(selected, 'latency') }} 秒</dd></dl><p class="admin-note">数据集版本绑定样例修订、偏好、来源快照与固定时钟。未执行或失败的评分显示“—”；规则、模型与人工评分分别标明，不把缺失结果当作零分。</p></section>
    <section class="admin-section"><div class="section-heading"><h2>逐样例结果</h2><span class="meta">{{ selected.results.length }} 项结果</span></div><EmptyState v-if="!selected.results.length" title="尚无逐项结果" description="实验开始执行后会在这里显示已固定的样例修订与评分。" /><section v-for="result in selected.results" :key="result.caseId" class="card admin-section"><div class="section-heading"><div><h3 class="mono admin-run-id">{{ result.caseId }}</h3><span class="meta">固定修订 {{ result.caseRevision }}</span></div><Badge :status="result.status" /></div><p v-if="!result.scores.length" class="meta">该样例尚未产生评分。</p><div v-else class="table-wrap" tabindex="0" role="region" :aria-label="`${result.caseId} 评分，可横向滚动`"><table class="data-table admin-table"><thead><tr><th>指标</th><th>来源</th><th>评分</th><th>规则判定 / 说明</th></tr></thead><tbody><tr v-for="score in result.scores" :key="`${score.metric}-${score.method}`"><td>{{ metricLabel[score.metric] }}</td><td>{{ methodLabel[score.method] }}</td><td>{{ number(score.value, 2) }}<span v-if="score.maximum != null"> / {{ score.maximum }}</span></td><td class="wide-cell">{{ score.passed == null ? '未判定' : score.passed ? '通过' : '未通过' }}<small v-if="score.error">{{ score.error }}</small></td></tr></tbody></table></div></section></section>
  </template></template>
  <template v-else><header class="page-header"><div><div class="eyebrow">EVALUATION LAB</div><h1>每次调整，都有参照</h1><p>固定样例、相同尺度，比较配置改变带来的影响。</p></div><button class="button" :disabled="loading || referencesLoading" @click="collection.load(); loadReferences()"><RefreshCw :size="16" />刷新</button></header><nav class="tabs" aria-label="评估视图"><button :aria-pressed="tab === 'experiments'" @click="tab = 'experiments'">实验记录</button><button :aria-pressed="tab === 'compare'" @click="tab = 'compare'">A / B 对比</button><button :aria-pressed="tab === 'cases'" @click="tab = 'cases'">固定样例 <span class="meta">{{ cases.length }}</span></button></nav><p v-if="error || loadError || referenceError" class="alert alert--danger" role="alert">{{ error || loadError || referenceError }}</p>
    <template v-if="tab === 'experiments'"><section class="card"><div class="section-heading"><h2>运行一次实验</h2><span class="meta">{{ referencesLoaded ? `使用 ${cases.length} 个当前固定样例` : referencesLoading ? '正在加载固定样例…' : '固定样例尚未加载' }}</span></div><p>使用当前部署的 Agent 运行固定样例，实验记录会保留本次使用的配置版本。</p><div class="actions"><button class="button button--primary" :disabled="!!busy || !cases.length || !referencesLoaded" @click="run"><Play :size="16" />{{ busy === 'run' ? '正在创建…' : '运行评估' }}</button><button v-if="referencesLoaded && !cases.length" class="button" @click="tab = 'cases'">准备固定样例</button></div><p class="admin-note">实验创建时固定当前样例修订和配置；不会向真实用户发布简报。模型评分不可用时保留未评分状态，可根据逐项结果检查服务端模型配置。</p></section>
      <div v-if="loading && !loaded" class="skeleton admin-section" role="status" aria-label="加载实验列表"></div><EmptyState v-else-if="!items.length" title="还没有可显示的评估实验" :description="loadError || '准备固定样例后，使用当前部署配置运行第一组实验。'" /><template v-else><div class="section-heading admin-section"><h2>实验记录</h2><button class="button button--ghost" @click="tab = 'compare'">比较结果 →</button></div><div class="table-wrap" tabindex="0" role="region" aria-label="实验列表，可横向滚动"><table class="data-table admin-table"><thead><tr><th>实验</th><th>配置 / 样例</th><th>状态</th><th>相关性 / 忠实度</th><th>引用</th><th>费用（USD）</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td class="wide-cell"><RouterLink :to="`/evaluations/${item.id}`">{{ item.name }}</RouterLink><small>{{ formatDate(item.createdAt) }}</small></td><td>{{ item.configVersion }}<small>{{ item.cases }} 个样例</small></td><td><Badge :status="item.status" /></td><td>{{ value(item, 'relevance') }} / {{ value(item, 'faithfulness') }}<small>模型评分 · 满分 5</small></td><td>{{ value(item, 'citations') }}%</td><td>{{ value(item, 'cost') }}</td></tr></tbody></table></div></template>
    </template>
    <template v-else-if="tab === 'compare'"><section class="card"><h2>选择两次实验</h2><div class="form-grid"><label class="field">实验 A · 基线<select v-model="firstId" class="field-control"><option value="">选择实验</option><option v-for="item in items" :key="item.id" :value="item.id">{{ item.name }} · {{ item.configVersion }}</option></select></label><label class="field">实验 B · 对照<select v-model="secondId" class="field-control"><option value="">选择实验</option><option v-for="item in items" :key="item.id" :value="item.id">{{ item.name }} · {{ item.configVersion }}</option></select></label></div><p class="admin-note">比较使用相同数据集与评分器版本的两次实验。样例数量相同不代表输入相同。</p></section><EmptyState v-if="!first || !second" title="选择两个实验开始比较" description="选择已加载的实验，或加载更多历史记录。" /><p v-else-if="firstId === secondId" class="alert admin-section">请选择两次不同的实验。</p><template v-else><p v-if="!comparable" class="alert admin-section">数据集或评分器版本不同，以下数值仅供查看，不计算配置变化带来的差值。</p><div class="table-wrap admin-section" tabindex="0" role="region" aria-label="实验对比，可横向滚动"><table class="data-table admin-table"><thead><tr><th>指标与来源</th><th>A · {{ first.configVersion }}</th><th>B · {{ second.configVersion }}</th><th>B − A</th></tr></thead><tbody><tr v-for="metric in metrics" :key="metric.key"><td>{{ metric.label }}<small>{{ metric.source }}</small></td><td>{{ value(first, metric.key) }} {{ metric.unit }}</td><td>{{ value(second, metric.key) }} {{ metric.unit }}</td><td>{{ delta(metric.key) }}</td></tr></tbody></table></div><details class="card admin-section"><summary>输入与评分器版本</summary><dl class="admin-kv"><dt>A 数据集</dt><dd class="mono">{{ first.datasetVersion }}</dd><dt>B 数据集</dt><dd class="mono">{{ second.datasetVersion }}</dd><dt>A 评分器</dt><dd class="mono">{{ first.scorerVersion }}</dd><dt>B 评分器</dt><dd class="mono">{{ second.scorerVersion }}</dd></dl></details></template></template>
    <template v-else><div class="section-heading"><h2>固定样例集</h2><button class="button button--primary" @click="edit()"><Plus :size="16" />添加样例</button></div><div v-if="referencesLoading && !referencesLoaded" class="skeleton" role="status" aria-label="加载固定样例"></div><EmptyState v-else-if="!cases.length" title="还没有固定样例" :description="referenceError || '用偏好与预期行为定义可重复检查，保存时固定来源与时钟。'" /><section v-else class="card"><ul class="admin-list"><li v-for="item in cases" :key="item.id"><div class="section-heading"><h3>{{ item.name }} <span class="meta">修订 {{ item.revision }}</span></h3><button class="button button--ghost" @click="edit(item)">编辑</button></div><p class="muted">偏好：{{ item.preference }}</p><p class="meta">预期：{{ item.expected }}</p><details><summary class="meta">固定输入 · {{ item.sourceSnapshotIds.length }} 个来源快照</summary><dl class="admin-kv"><dt>固定时钟</dt><dd>{{ formatDate(item.fixedAt) }}</dd><dt>快照 ID</dt><dd class="mono">{{ item.sourceSnapshotIds.join('、') || '显式无证据样例' }}</dd></dl><pre>{{ JSON.stringify(item.preferenceSnapshot, null, 2) }}</pre></details></li></ul></section></template>
    <div v-if="tab !== 'cases'" class="admin-pagination"><span class="meta">{{ scope }}</span><button v-if="nextCursor" class="button" :disabled="loading" @click="collection.load(true)">加载更多实验</button></div>
  </template>
  <Modal :open="editing" :title="editId ? '编辑固定样例' : '添加固定样例'" @close="close"><form id="case-form" class="admin-form stack" @submit.prevent="save"><p v-if="formError" class="alert alert--danger" role="alert">{{ formError }}</p><label class="field">样例名称<input v-model="form.name" class="field-control" required maxlength="120"></label><label class="field">用户偏好输入<textarea v-model="form.preference" class="field-control" required maxlength="2000"></textarea></label><label class="field">预期行为与检查标准<textarea v-model="form.expected" class="field-control" required maxlength="2000"></textarea></label><details><summary>固定输入设置</summary><div class="stack admin-section"><label class="field">固定时钟（ISO 时间，可留空）<input v-model="fixedAt" class="field-control" placeholder="2026-09-19T00:00:00Z"><span class="meta">新建留空由服务器保存当前时刻；编辑留空保留原时刻。</span></label><label class="field">来源快照<select v-model="snapshotMode" class="field-control"><option value="capture">{{ editId ? '保留原快照集合' : '保存时捕获当前可用快照' }}</option><option value="explicit">指定固定快照 ID</option></select></label><label v-if="snapshotMode === 'explicit'" class="field">快照 ID（每行一个）<textarea v-model="snapshotText" class="field-control" placeholder="留空表示无证据测试样例"></textarea><span class="meta">留空会固定空快照集合，不会在运行时联网补充。</span></label><label class="field">结构化偏好（JSON，可留空）<textarea v-model="preferencesText" class="field-control mono" rows="6"></textarea><span class="meta">包含 version、role、topics、keywords。留空使用偏好描述；编辑时留空保留原结构化偏好。</span></label></div></details></form><template #footer><button class="button" :disabled="!!busy" @click="close">取消</button><button class="button button--primary" type="submit" form="case-form" :disabled="!!busy">{{ busy === 'case' ? '保存中…' : '保存样例' }}</button></template></Modal>
</template>
