<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { Plus, RefreshCw, KeyRound } from 'lucide-vue-next';
import type { ModelConfig, ModelWrite, ConnectionTest } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue'; import Modal from '@ui/Modal.vue'; import EmptyState from '@ui/EmptyState.vue';
import { request, errorText, formatDate, notify, useCollection, useDirty } from '../lib';
const collection = useCollection<ModelConfig>('listModels'); const { items, loading, loaded, error: loadError, nextCursor, scope } = collection;
const busy = ref(''); const error = ref(''); const editing = ref(false); const editId = ref(''); const formError = ref(''); const results = ref<Record<string, ConnectionTest>>({}); const revokeTarget = ref<ModelConfig | null>(null);
const emptyForm = (): ModelWrite => ({ name: '', provider: 'OpenAI Compatible', modelId: '', endpoint: '', role: '主模型', contextWindow: 128000 });
const form = ref<ModelWrite>(emptyForm()); const secret = ref(''); const baseline = ref(''); const dirty = computed(() => editing.value && (JSON.stringify(form.value) !== baseline.value || !!secret.value)); const confirmDiscard = useDirty(dirty);
function edit(model?: ModelConfig) { editId.value = model?.id || ''; form.value = model ? { name: model.name, provider: model.provider, modelId: model.modelId, endpoint: model.endpoint, role: model.role, contextWindow: model.contextWindow } : emptyForm(); baseline.value = JSON.stringify(form.value); secret.value = ''; formError.value = ''; editing.value = true; }
function close() { if (!busy.value && confirmDiscard()) { editing.value = false; secret.value = ''; } }
async function save() { if (busy.value) return; busy.value = 'save'; formError.value = ''; try { const updated = await request<ModelConfig>(editId.value ? 'saveModel' : 'createModel', { path: editId.value ? { id: editId.value } : undefined, body: { ...form.value, name: form.value.name.trim(), modelId: form.value.modelId.trim(), endpoint: form.value.endpoint.trim(), ...(secret.value ? { apiKey: secret.value } : {}) } }); collection.replace(updated); delete results.value[updated.id]; editing.value = false; secret.value = ''; notify('模型配置已保存。请完成连接与能力测试。'); } catch (err) { formError.value = errorText(err); } finally { busy.value = ''; } }
async function toggle(model: ModelConfig) { busy.value = model.id; error.value = ''; try { collection.replace(await request<ModelConfig>('setModelEnabled', { path: { id: model.id }, body: { enabled: !model.enabled } })); notify(model.enabled ? '模型已停用。' : '模型已启用。'); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
async function test(model: ModelConfig) { busy.value = model.id; error.value = ''; try { const result = await request<ConnectionTest>('testModel', { path: { id: model.id } }); results.value[model.id] = result; collection.replace({ ...model, verified: result.verified }); notify(result.verified ? '连接与所需能力测试通过。' : '测试未通过，请查看模型下方的结果。'); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
async function revoke() { const model = revokeTarget.value; if (!model || busy.value) return; busy.value = model.id; error.value = ''; try { await request<void>('revokeModelSecret', { path: { id: model.id } }); collection.replace({ ...model, keyMasked: '', verified: false }); delete results.value[model.id]; revokeTarget.value = null; notify('该模型密钥已撤销。'); } catch (err) { error.value = errorText(err); } finally { busy.value = ''; } }
onMounted(() => collection.load());
</script>
<template><header class="page-header"><div><div class="eyebrow">MODEL CONNECTIONS</div><h1>为每个任务，配置合适的模型</h1><p>管理连接、模型角色与能力验证。</p></div><div class="actions"><button class="button" :disabled="loading" @click="collection.load()"><RefreshCw :size="16" />刷新</button><button class="button button--primary" @click="edit()"><Plus :size="16" />添加模型</button></div></header><p v-if="(error || loadError) && !revokeTarget" class="alert alert--danger" role="alert">{{ error || loadError }}</p>
  <div v-if="loading && !loaded" class="skeleton" role="status" aria-label="加载模型列表"></div><EmptyState v-else-if="!items.length" title="还没有可显示的模型" :description="loadError || '添加模型连接，并测试工具调用与结构化输出能力。'"><button v-if="loadError" class="button" @click="collection.load()">重试</button></EmptyState>
  <div v-else class="table-wrap" tabindex="0" role="region" aria-label="模型列表，可横向滚动"><table class="data-table admin-table"><thead><tr><th>模型 / 连接</th><th>角色 / 上下文</th><th>状态</th><th>凭据</th><th>操作</th></tr></thead><tbody><tr v-for="model in items" :key="model.id"><td class="wide-cell"><strong>{{ model.name }}</strong><small>{{ model.provider }} · {{ model.modelId }}</small><small class="mono">{{ model.endpoint }}</small><div v-if="results[model.id]" class="admin-connection"><p :class="results[model.id].verified ? 'field-success' : 'field-error'" role="status">{{ results[model.id].message }}</p><small>{{ formatDate(results[model.id].testedAt) }} · {{ results[model.id].capabilities.join(' / ') || '未确认能力' }}</small></div></td><td>{{ model.role }}<small>{{ model.contextWindow.toLocaleString() }} Token</small></td><td><Badge :status="model.enabled ? (model.verified ? 'healthy' : 'unverified') : 'disabled'" /></td><td class="admin-secret"><span class="mono">{{ model.keyMasked || '未配置密钥' }}</span></td><td><div class="actions"><button class="button button--small" :disabled="!!busy" @click="edit(model)">编辑</button><button class="button button--small" :disabled="!!busy" @click="test(model)">{{ busy === model.id ? '处理中…' : '测试连接' }}</button><button class="button button--small" :disabled="!!busy" @click="toggle(model)">{{ model.enabled ? '停用' : '启用' }}</button></div><button v-if="model.keyMasked" class="button button--ghost button--danger admin-section" :disabled="!!busy" @click="error = ''; revokeTarget = model"><KeyRound :size="15" />撤销密钥</button></td></tr></tbody></table></div><div class="admin-pagination"><span class="meta">{{ scope }}</span><button v-if="nextCursor" class="button" :disabled="loading" @click="collection.load(true)">加载更多</button></div><p class="admin-note">测试会发起真实请求，结果由服务端返回。验证未通过的模型不能作为已发布配置的新连接。</p>
  <Modal :open="editing" :title="editId ? '编辑模型连接' : '添加模型连接'" @close="close"><form id="model-form" class="admin-form stack" @submit.prevent="save"><p v-if="formError" class="alert alert--danger" role="alert">{{ formError }}</p><label class="field">显示名称<input v-model="form.name" class="field-control" required maxlength="120"></label><div class="form-grid"><label class="field">提供商名称<input v-model="form.provider" class="field-control" required placeholder="兼容 OpenAI API 的提供商"></label><label class="field">角色<select v-model="form.role" class="field-control"><option>主模型</option><option>摘要模型</option><option>评估模型</option><option>子模型</option></select></label></div><label class="field">模型 ID<input v-model="form.modelId" class="field-control" required placeholder="提供商给出的模型标识"></label><label class="field">API 连接地址<input v-model="form.endpoint" class="field-control" type="url" required placeholder="https://…/v1"><span class="meta">当前使用 OpenAI 兼容接口，地址填写服务的 API base URL。</span></label><label class="field">上下文窗口（Token）<input v-model.number="form.contextWindow" class="field-control" type="number" min="1" step="1" required></label><label class="field">{{ editId ? '替换 API Key（留空保留）' : 'API Key（可选）' }}<input v-model="secret" class="field-control" type="password" autocomplete="new-password" maxlength="4096"><span class="meta">密钥仅用于提交，保存后不会从服务器返回。</span></label></form><template #footer><button class="button" :disabled="!!busy" @click="close">取消</button><button class="button button--primary" form="model-form" type="submit" :disabled="!!busy">{{ busy === 'save' ? '保存中…' : '保存连接' }}</button></template></Modal>
  <Modal :open="!!revokeTarget" title="撤销模型密钥" @close="!busy && (revokeTarget = null)"><p>撤销“{{ revokeTarget?.name }}”的密钥后，该连接需要重新配置并验证。</p><p v-if="error" class="alert alert--danger" role="alert">{{ error }}</p><template #footer><button class="button" :disabled="!!busy" @click="revokeTarget = null">取消</button><button class="button button--danger" :disabled="!!busy" @click="revoke">{{ busy ? '撤销中…' : '撤销密钥' }}</button></template></Modal>
</template>
