<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RefreshCw, ArrowUpRight, Radio, Activity, Send } from 'lucide-vue-next';
import type { HealthSummary, AgentRun, Source, Delivery } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue';
import EmptyState from '@ui/EmptyState.vue';
import { request, errorText, formatDate, number, type Page } from '../lib';
const summary = ref<HealthSummary | null>(null); const runs = ref<AgentRun[]>([]); const sources = ref<Source[]>([]); const deliveries = ref<Delivery[]>([]); const loading = ref(false); const error = ref('');
async function load() { if (loading.value) return; loading.value = true; error.value = ''; try { const data = await Promise.all([request<HealthSummary>('getOverview'), request<Page<AgentRun>>('listAdminRuns', { query: { limit: 5 } }), request<Page<Source>>('listSources', { query: { limit: 5 } }), request<Page<Delivery>>('listAdminDeliveries', { query: { limit: 5 } })]); summary.value = data[0]; runs.value = data[1].items; sources.value = data[2].items; deliveries.value = data[3].items; } catch (err) { error.value = errorText(err); } finally { loading.value = false; } }
onMounted(load);
</script>
<template><header class="page-header"><div><div class="eyebrow">CONTROL CENTER</div><h1>今天，一切井然有序</h1><p>观察内容采集、Agent 运行和站内发布。</p></div><button class="button" :disabled="loading" @click="load"><RefreshCw :size="16" />{{ loading ? '刷新中…' : '刷新概览' }}</button></header>
  <div v-if="loading && !summary" class="skeleton" role="status" aria-label="正在加载概览"></div><EmptyState v-else-if="!summary && error" title="概览加载失败" :description="error" error><button class="button" @click="load">重试</button></EmptyState>
  <template v-if="summary"><p v-if="error" class="alert alert--danger" role="alert">{{ error }} 当前保留上次成功获取的数据。</p><p class="meta">统计更新于 {{ formatDate(summary.generatedAt) }}</p><div class="metric-grid"><div class="metric"><span class="meta">活跃运行</span><strong>{{ summary.activeRuns }}</strong><RouterLink to="/runs">查看运行 →</RouterLink></div><div class="metric"><span class="meta">异常来源</span><strong>{{ summary.failedSources }}</strong><RouterLink to="/sources">检查来源 →</RouterLink></div><div class="metric"><span class="meta">发布失败</span><strong>{{ summary.failedDeliveries }}</strong><RouterLink to="/deliveries">处理投递 →</RouterLink></div><div class="metric"><span class="meta">运行完成率</span><strong>{{ summary.completionRate == null ? '—' : number(summary.completionRate * 100, 1) + '%' }}</strong><span class="meta">服务端统计 {{ summary.sampleCount }} 次运行</span></div></div>
    <div class="admin-grid"><section class="card"><div class="section-heading"><h2><Activity :size="18" />最近运行</h2><RouterLink to="/runs" aria-label="查看全部运行"><ArrowUpRight :size="18" /></RouterLink></div><ul v-if="runs.length" class="admin-list"><li v-for="run in runs" :key="run.id"><div class="section-heading"><RouterLink :to="`/runs/${run.id}`">{{ run.userName }}的简报</RouterLink><Badge :status="run.status" /></div><p class="meta">{{ run.model }} · {{ formatDate(run.startedAt) }}</p></li></ul><p v-else class="muted">暂无运行记录。</p></section>
    <section class="card"><div class="section-heading"><h2><Radio :size="18" />新闻来源</h2><RouterLink to="/sources" aria-label="查看全部来源"><ArrowUpRight :size="18" /></RouterLink></div><ul v-if="sources.length" class="admin-list"><li v-for="source in sources" :key="source.id"><div class="section-heading"><RouterLink :to="`/sources/${source.id}`">{{ source.name }}</RouterLink><Badge :status="source.status" /></div><p class="meta">{{ source.items }} 条 · {{ source.stale ? '缓存待更新' : '缓存有效' }} · {{ formatDate(source.lastSuccess) }}</p></li></ul><p v-else class="muted">还没有配置新闻来源。</p></section>
    <section class="card"><div class="section-heading"><h2><Send :size="18" />最近投递</h2><RouterLink to="/deliveries">查看投递 →</RouterLink></div><ul v-if="deliveries.length" class="admin-list"><li v-for="delivery in deliveries" :key="delivery.id"><div class="section-heading"><strong>{{ delivery.userName }}</strong><Badge :status="delivery.status" /></div><p class="meta">{{ delivery.error || formatDate(delivery.time) }}</p></li></ul><p v-else class="muted">暂无站内投递记录。</p></section></div><p class="admin-note">各列表展示最近 5 条记录；汇总指标由服务端统计。站内发布不代表用户已读。</p>
  </template>
</template>
