<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, Square, RefreshCw } from 'lucide-vue-next';
import { subscribeRunEvents, type AgentRun } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue'; import EmptyState from '@ui/EmptyState.vue'; import RunTimeline from '@ui/RunTimeline.vue';
import { request, errorText, formatDate, number, useCollection, useRefresh, notify } from '../lib';
const route = useRoute(); const router = useRouter(); const search = ref('');
const status = computed({ get: () => String(route.query.status || ''), set: value => { void router.replace({ query: { ...route.query, status: value || undefined } }); } });
const model = computed({ get: () => String(route.query.model || ''), set: value => { void router.replace({ query: { ...route.query, model: value || undefined } }); } });
const date = computed({ get: () => String(route.query.date || ''), set: value => { void router.replace({ query: { ...route.query, date: value || undefined } }); } });
function query() { const start = date.value ? new Date(`${date.value}T00:00:00+08:00`) : null; return { status: status.value || undefined, model: model.value || undefined, from: start?.toISOString(), to: start ? new Date(start.getTime() + 86400000 - 1).toISOString() : undefined }; }
const collection = useCollection<AgentRun>('listAdminRuns', query); const { items, loaded, loading, error: loadError, nextCursor, scope } = collection;
const filtered = computed(() => items.value.filter(run => `${run.id} ${run.userName}`.toLowerCase().includes(search.value.trim().toLowerCase())));
const run = ref<AgentRun | null>(null); const detailLoading = ref(false); const error = ref(''); const streamError = ref(''); const busy = ref(false); const connection = ref<'connecting' | 'open' | 'reconnecting' | 'closed'>('closed');
let stopStream: (() => void) | undefined; let revision = 0;
const active = computed(() => run.value && ['queued', 'running', 'cancelling'].includes(run.value.status));
const canCancel = computed(() => run.value && ['queued', 'running'].includes(run.value.status));
const totalTokens = (item: AgentRun) => item.inputTokens == null || item.outputTokens == null ? '—' : number(item.inputTokens + item.outputTokens);
async function detail(refresh = false) {
  if (detailLoading.value) return;
  const id = String(route.params.id || ''); if (!id) return;
  const current = revision; detailLoading.value = true; if (!refresh) error.value = '';
  try { const updated = await request<AgentRun>('getAdminRun', { path: { id } }); if (current !== revision) return; const events = new Map([...(run.value?.events || []), ...updated.events].map(event => [event.id, event])); run.value = { ...updated, events: [...events.values()].sort((a, b) => a.id - b.id) }; error.value = '';
    if (!active.value) { stopStream?.(); stopStream = undefined; connection.value = 'closed'; }
    else if (!stopStream) startStream(id);
  } catch (err) { if (current === revision) error.value = errorText(err); } finally { if (current === revision) detailLoading.value = false; }
}
function startStream(id: string) { const current = revision; stopStream = subscribeRunEvents(id, { afterId: run.value?.events.at(-1)?.id || 0, onEvent: event => { if (current !== revision || !run.value) return; const events = new Map([...run.value.events, event].map(item => [item.id, item])); run.value = { ...run.value, events: [...events.values()].sort((a, b) => a.id - b.id) }; void detail(true); }, onStatus: next => { if (current === revision) { connection.value = next; if (next === 'open') streamError.value = ''; } }, onError: err => { if (current === revision) streamError.value = errorText(err); } }); }
async function cancel() { if (!run.value || busy.value) return; busy.value = true; error.value = ''; try { run.value = await request<AgentRun>('cancelAdminRun', { path: { id: run.value.id } }); notify(run.value.status === 'cancelled' ? '运行已取消。' : '取消请求已提交，等待运行确认。'); } catch (err) { error.value = errorText(err); } finally { busy.value = false; } }
watch(() => route.params.id, () => { revision++; stopStream?.(); stopStream = undefined; run.value = null; detailLoading.value = false; error.value = ''; streamError.value = ''; connection.value = 'closed'; if (route.params.id) void detail(); else void collection.load(); }, { immediate: true });
watch(() => [status.value, model.value, date.value], () => { if (!route.params.id) void collection.load(); });
useRefresh(() => { if (route.params.id && active.value && !detailLoading.value) return detail(true); }, 5000);
onBeforeUnmount(() => { revision++; stopStream?.(); });
</script>
<template><template v-if="route.params.id"><RouterLink class="admin-back" :to="{ path: '/runs', query: route.query }"><ArrowLeft :size="16" />全部运行</RouterLink><div v-if="detailLoading && !run" class="skeleton" role="status" aria-label="加载运行详情"></div><EmptyState v-else-if="!run" title="无法加载这次运行" :description="error || '运行不存在或已不可访问。'" error><button class="button" @click="detail()">重试</button></EmptyState>
  <template v-if="run"><header class="page-header"><div><div class="eyebrow">RUN TRACE</div><h1>{{ run.userName }}的每日简报</h1><p class="meta mono admin-run-id">{{ run.id }} · {{ formatDate(run.startedAt) }}</p></div><div class="actions"><Badge :status="run.status" /><button class="button" :disabled="detailLoading" @click="detail()"><RefreshCw :size="16" />刷新</button><button v-if="canCancel || run.status === 'cancelling'" class="button" :disabled="busy || run.status === 'cancelling'" @click="cancel"><Square :size="14" />{{ busy || run.status === 'cancelling' ? '正在取消…' : '取消运行' }}</button></div></header><p v-if="error" class="alert alert--danger" role="alert">{{ error }} 当前保留已收到的运行记录。</p><p v-if="run.status === 'partial'" class="alert">本次运行部分完成，可用内容已保留，具体缺失与恢复情况见事件。</p>
    <section class="card"><div class="admin-run-meta"><div><span class="meta">耗时</span><strong>{{ number(run.elapsedSeconds, 1) }} 秒</strong></div><div><span class="meta">输入 / 输出 Token</span><strong>{{ number(run.inputTokens) }} / {{ number(run.outputTokens) }}</strong></div><div><span class="meta">费用（USD）</span><strong>{{ number(run.cost, 4) }}</strong></div><div><span class="meta">搜索次数</span><strong>{{ run.searchCount }}</strong></div></div><p class="admin-note">“—”表示用量或价格不可用；费用基于提供商报告的用量与配置价格计算。</p></section>
    <section class="card admin-section"><h2>运行配置</h2><dl class="admin-kv"><dt>模型</dt><dd>{{ run.model }}</dd><dt>配置版本</dt><dd>{{ run.configVersion }}</dd></dl><p class="meta">事件仅展示授权的参数与结果摘要，密钥和模型私有思考不进入追踪内容。</p><RouterLink to="/agent-configs">查看配置版本 →</RouterLink></section>
    <section class="admin-section"><div class="section-heading"><h2>事件与子任务</h2><span class="meta">按事件 ID 持久化回放</span></div><p v-if="active" class="alert" :class="connection === 'open' ? 'alert--info' : ''" role="status">{{ connection === 'open' ? '实时事件已连接。' : connection === 'connecting' ? '正在连接实时事件…' : '实时连接中断，正在重新连接。已接收事件保留，后台运行状态单独刷新。' }}<span v-if="streamError">{{ streamError }}</span></p><RunTimeline :run="run" technical /></section>
    <section v-if="['completed','partial'].includes(run.status)" class="card admin-section"><h2>生成与发布</h2><p>本次运行已达到{{ run.status === 'partial' ? '部分完成' : '完成' }}状态。站内发布结果在投递记录中单独记录。</p><RouterLink to="/deliveries">查看投递记录 →</RouterLink></section>
  </template></template>
  <template v-else><header class="page-header"><div><div class="eyebrow">AGENT OBSERVABILITY</div><h1>运行观察</h1><p>从一次简报，追溯模型、工具与子任务的实际事件。</p></div><button class="button" :disabled="loading" @click="collection.load()"><RefreshCw :size="16" />刷新运行</button></header><p v-if="loadError" class="alert alert--danger" role="alert">{{ loadError }}</p><div class="admin-toolbar"><label class="field">用户或运行 ID<input v-model="search" class="field-control" type="search" placeholder="筛选已加载记录"></label><label class="field">状态<select v-model="status" class="field-control"><option value="">全部状态</option><option value="queued">排队中</option><option value="running">运行中</option><option value="cancelling">取消中</option><option value="completed">已完成</option><option value="partial">部分完成</option><option value="failed">失败</option><option value="cancelled">已取消</option></select></label><label class="field">模型名称<input v-model.lazy="model" class="field-control" placeholder="模型名称"></label><label class="field">运行日期<input v-model="date" class="field-control" type="date"></label></div><div v-if="search || status || model || date" class="actions"><span class="meta">{{ filtered.length }} 条已加载匹配记录</span><button class="button button--ghost" @click="search = ''; router.replace({ query: {} })">清除筛选</button></div>
    <div v-if="loading && !loaded" class="skeleton" role="status" aria-label="加载运行列表"></div><EmptyState v-else-if="!filtered.length" title="没有匹配的运行" :description="loadError || '运行由用户请求或每日计划创建，可调整筛选后查看。'"><button v-if="loadError" class="button" @click="collection.load()">重试</button></EmptyState><div v-else class="table-wrap" tabindex="0" role="region" aria-label="运行列表，可横向滚动"><table class="data-table admin-table"><thead><tr><th>运行 / 用户</th><th>状态</th><th>模型 / 配置</th><th>开始时间</th><th>耗时 / Token</th><th>费用（USD）</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td class="wide-cell"><RouterLink :to="{ path: `/runs/${item.id}`, query: route.query }">{{ item.userName }}的每日简报</RouterLink><small class="mono">{{ item.id }}</small></td><td><Badge :status="item.status" /></td><td>{{ item.model }}<small>{{ item.configVersion }}</small></td><td class="nowrap">{{ formatDate(item.startedAt) }}</td><td class="nowrap">{{ number(item.elapsedSeconds, 1) }} 秒<small>{{ totalTokens(item) }} Token</small></td><td>{{ number(item.cost, 4) }}</td></tr></tbody></table></div><div class="admin-pagination"><span class="meta">{{ scope }} · 用户 / ID 仅筛选已加载记录</span><button v-if="nextCursor" class="button" :disabled="loading" @click="collection.load(true)">加载更多</button></div>
  </template>
</template>
