<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { ArrowLeft, Plus, RefreshCw, Pencil, Pause, Play } from 'lucide-vue-next';
import type { Source, SourceWrite } from '@zhigenews/api-client';
import Badge from '@ui/Badge.vue';
import Modal from '@ui/Modal.vue';
import EmptyState from '@ui/EmptyState.vue';
import { request, errorText, formatDate, notify, useCollection, useDirty, useRefresh, intentKeys } from '../lib';
const route = useRoute(); const collection = useCollection<Source>('listSources');
const { items, loading, loaded, error: loadError, nextCursor, scope } = collection;
const search = ref(''); const kind = ref('all'); const selected = ref<Source | null>(null); const detailLoading = ref(false); const detailError = ref('');
const busy = ref(''); const actionError = ref(''); const editing = ref(false); const editId = ref(''); const formError = ref('');
const emptyForm = (): SourceWrite => ({ name: '', kind: 'rss', sourceId: '', url: '', interval: 3600 });
const form = ref<SourceWrite>(emptyForm()); const initialForm = ref(''); const dirty = computed(() => editing.value && JSON.stringify(form.value) !== initialForm.value); const confirmDiscard = useDirty(dirty); const keys = intentKeys();
const filtered = computed(() => items.value.filter(item => (kind.value === 'all' || item.kind === kind.value) && `${item.name} ${item.id} ${item.sourceId}`.toLowerCase().includes(search.value.trim().toLowerCase())));
function edit(source?: Source) { editId.value = source?.id || ''; form.value = source ? { name: source.name, kind: source.kind, sourceId: source.sourceId, url: source.url, interval: source.interval } : emptyForm(); initialForm.value = JSON.stringify(form.value); formError.value = ''; editing.value = true; }
function close() { if (!busy.value && confirmDiscard()) { editing.value = false; formError.value = ''; } }
async function save() { if (busy.value) return; busy.value = 'save'; formError.value = ''; try { const source = await request<Source>(editId.value ? 'saveSource' : 'createSource', { path: editId.value ? { id: editId.value } : undefined, body: { ...form.value, name: form.value.name.trim(), sourceId: form.value.sourceId.trim(), url: form.value.url.trim() } }); collection.replace(source); if (selected.value?.id === source.id) selected.value = source; editing.value = false; notify('来源已保存，采集状态将由后台更新。'); } catch (error) { formError.value = errorText(error); } finally { busy.value = ''; } }
async function act(source: Source, operation: 'fetchSource' | 'setSourceEnabled') { if (busy.value) return; busy.value = source.id; actionError.value = ''; try { const updated = await request<Source>(operation, { path: { id: source.id }, ...(operation === 'fetchSource' ? { idempotencyKey: keys.get(source.id) } : { body: { enabled: source.status === 'disabled' } }) }); collection.replace(updated); if (selected.value?.id === updated.id) selected.value = updated; if (operation === 'fetchSource') { keys.done(source.id); notify('采集请求已排队。请等待后台更新；仍会遵守来源周期与退避时间。'); } else notify(updated.status === 'disabled' ? '来源已停用。' : '来源已启用。'); } catch (error) { actionError.value = errorText(error); } finally { busy.value = ''; } }
let detailRevision = 0;
async function loadDetail() { const id = String(route.params.id || ''); if (!id) { selected.value = null; return; } const revision = ++detailRevision; detailLoading.value = true; detailError.value = ''; try { const source = await request<Source>('getSource', { path: { id } }); if (revision === detailRevision) selected.value = source; } catch (error) { if (revision === detailRevision) detailError.value = errorText(error); } finally { if (revision === detailRevision) detailLoading.value = false; } }
watch(() => route.params.id, () => { detailRevision++; selected.value = null; void loadDetail(); }, { immediate: true });
onMounted(() => collection.load());
useRefresh(() => { if (busy.value || editing.value) return; if (route.params.id) return loadDetail(); if (items.value.some(item => item.status === 'syncing')) return collection.load(); }, 5000);
</script>
<template>
  <template v-if="route.params.id"><RouterLink class="admin-back" to="/sources"><ArrowLeft :size="16" />全部新闻来源</RouterLink><div v-if="detailLoading && !selected" class="skeleton" role="status" aria-label="加载来源详情"></div><EmptyState v-else-if="!selected" title="无法加载这个来源" :description="detailError || '来源不存在或已不可访问。'" error><button class="button" @click="loadDetail">重试</button></EmptyState>
    <template v-if="selected"><header class="page-header"><div><div class="eyebrow">SOURCE DETAIL</div><h1>{{ selected.name }}</h1><p>{{ selected.kind === 'newsnow' ? 'NewsNow' : 'RSS' }} · {{ selected.sourceId || selected.id }}</p></div><div class="actions"><Badge :status="selected.status" /><button class="button" :disabled="!!busy" @click="edit(selected)"><Pencil :size="16" />编辑来源</button><button class="button button--primary" :disabled="!!busy || selected.status === 'disabled' || selected.status === 'syncing'" @click="act(selected, 'fetchSource')"><RefreshCw :size="16" />{{ busy === selected.id ? '正在提交…' : '请求采集' }}</button></div></header>
      <p v-if="actionError || detailError" class="alert alert--danger" role="alert">{{ actionError || detailError }}</p><p v-if="selected.error" class="alert alert--danger">{{ selected.error }}</p><p v-if="selected.stale" class="alert">{{ selected.snapshotId ? '缓存已过期，现有快照仍保留。请查看采集状态。' : '尚无有效快照，等待首次成功采集。' }}</p>
      <div class="metric-grid"><div class="metric"><span class="meta">当前条目</span><strong>{{ selected.items }}</strong></div><div class="metric"><span class="meta">有效采集周期</span><strong>{{ selected.interval }} <small>秒</small></strong></div><div class="metric"><span class="meta">上游周期</span><strong>{{ selected.upstreamInterval || '—' }} <small v-if="selected.upstreamInterval">秒</small></strong></div><div class="metric"><span class="meta">快照年龄</span><strong>{{ selected.cacheAgeSeconds ?? '—' }} <small v-if="selected.cacheAgeSeconds != null">秒</small></strong></div></div>
      <section class="card"><h2>连接与快照</h2><dl class="admin-kv"><dt>请求地址</dt><dd><a :href="selected.url" target="_blank" rel="noopener noreferrer">{{ selected.url }}</a></dd><dt>来源标识</dt><dd class="mono">{{ selected.id }}</dd><dt>最近尝试</dt><dd>{{ formatDate(selected.lastFetchedAt) }}</dd><dt>最近成功</dt><dd>{{ formatDate(selected.lastSuccess) }}</dd><dt>下次采集</dt><dd>{{ formatDate(selected.nextFetch) }}</dd><dt>内容变化</dt><dd>{{ formatDate(selected.lastChanged) }}</dd><dt>快照取得时间</dt><dd>{{ formatDate(selected.snapshotFetchedAt) }}</dd><dt>快照 ID</dt><dd class="mono">{{ selected.snapshotId || '尚无快照' }}</dd><dt>上游配置版本</dt><dd class="mono">{{ selected.upstreamRevision || '未提供' }}</dd><dt>缓存状态</dt><dd>{{ selected.stale ? '待更新' : '有效' }}</dd></dl><p class="admin-note">条件请求未发现变化时继续使用原快照；最近成功时间与快照内容取得时间分别记录。</p><button class="button" :disabled="!!busy" @click="act(selected, 'setSourceEnabled')"><component :is="selected.status === 'disabled' ? Play : Pause" :size="16" />{{ selected.status === 'disabled' ? '启用来源' : '停用来源' }}</button></section>
    </template>
  </template>
  <template v-else><header class="page-header"><div><div class="eyebrow">NEWS SOURCES</div><h1>从源头，保持信息新鲜</h1><p>管理 NewsNow 与 RSS，查看每次采集的真实状态。</p></div><div class="actions"><button class="button" :disabled="loading" @click="collection.load()"><RefreshCw :size="16" />刷新</button><button class="button button--primary" @click="edit()"><Plus :size="16" />添加来源</button></div></header>
    <p v-if="actionError || loadError" class="alert alert--danger" role="alert">{{ actionError || loadError }}{{ loaded ? ' 已保留上次数据。' : '' }}</p><div class="admin-toolbar"><label class="field">查找来源<input v-model="search" class="field-control" type="search" placeholder="名称或来源 ID"></label><label class="field">来源类型<select v-model="kind" class="field-control"><option value="all">全部类型</option><option value="newsnow">NewsNow</option><option value="rss">RSS</option></select></label></div>
    <div v-if="loading && !loaded" class="skeleton" role="status" aria-label="加载来源列表"></div><EmptyState v-else-if="!filtered.length" :title="loaded ? '没有匹配的来源' : '来源列表暂不可用'" :description="loadError || '添加新闻来源，或调整筛选条件。'"><button v-if="loadError" class="button" @click="collection.load()">重试</button></EmptyState>
    <div v-else class="table-wrap" tabindex="0" role="region" aria-label="新闻来源列表，可横向滚动"><table class="data-table admin-table"><thead><tr><th>来源</th><th>状态 / 条目</th><th>采集周期</th><th>最近成功 / 下次采集</th><th>操作</th></tr></thead><tbody><tr v-for="source in filtered" :key="source.id"><td class="wide-cell"><RouterLink :to="`/sources/${source.id}`">{{ source.name }}</RouterLink><small>{{ source.kind }} · {{ source.sourceId || source.id }}</small></td><td><Badge :status="source.status" /><small>{{ source.items }} 条 · {{ source.stale ? '待更新' : '缓存有效' }}</small></td><td class="nowrap">{{ source.interval }} 秒<small>上游 {{ source.upstreamInterval ? `${source.upstreamInterval} 秒` : '未提供' }}</small></td><td class="nowrap">{{ formatDate(source.lastSuccess) }}<small>{{ formatDate(source.nextFetch) }}</small></td><td><div class="actions"><button class="button button--small" :disabled="!!busy" @click="edit(source)">编辑</button><button class="button button--small" :disabled="!!busy || ['disabled','syncing'].includes(source.status)" @click="act(source, 'fetchSource')">采集</button><button class="button button--small" :disabled="!!busy" @click="act(source, 'setSourceEnabled')">{{ source.status === 'disabled' ? '启用' : '停用' }}</button></div><small v-if="source.error">{{ source.error }}</small></td></tr></tbody></table></div><div class="admin-pagination"><span class="meta">{{ scope }} · 筛选应用于已加载记录</span><button v-if="nextCursor" class="button" :disabled="loading" @click="collection.load(true)">{{ loading ? '加载中…' : '加载更多' }}</button></div>
  </template>
  <Modal :open="editing" :title="editId ? '编辑新闻来源' : '添加新闻来源'" @close="close"><form id="source-form" class="admin-form stack" @submit.prevent="save"><p v-if="formError" class="alert alert--danger" role="alert">{{ formError }}</p><label class="field">名称<input v-model="form.name" class="field-control" required maxlength="120"></label><div class="form-grid"><label class="field">类型<select v-model="form.kind" class="field-control"><option value="rss">RSS</option><option value="newsnow">NewsNow</option></select></label><label class="field">本地采集周期（秒）<input v-model.number="form.interval" class="field-control" type="number" min="1" step="1" required></label></div><label class="field">{{ form.kind === 'newsnow' ? 'NewsNow 来源 ID' : '来源标识（可选）' }}<input v-model="form.sourceId" class="field-control" :required="form.kind === 'newsnow'" placeholder="来源提供的稳定标识"></label><label class="field">{{ form.kind === 'newsnow' ? 'NewsNow API 地址' : 'RSS 地址' }}<input v-model="form.url" class="field-control" type="url" required placeholder="https://"></label><p class="meta">上游周期由服务器读取。本地有效周期不会短于 NewsNow 上游周期，失败后按退避时间重试。</p></form><template #footer><button class="button" :disabled="!!busy" @click="close">取消</button><button class="button button--primary" form="source-form" type="submit" :disabled="!!busy">{{ busy === 'save' ? '保存中…' : '保存来源' }}</button></template></Modal>
</template>
