<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, Plus, Play, FlaskConical, ArrowRight } from 'lucide-vue-next';
import { state, api, notify, formatDate } from '@shared/mock';
import type { EvalCase } from '@shared/types';
import Modal from '@shared/Modal.vue';
import Badge from '@shared/Badge.vue';
import EmptyState from '@shared/EmptyState.vue';
const route = useRoute(); const router = useRouter();
const tab = ref('experiments'); const busy = ref(''); const error = ref(''); const editing = ref(false);
const configVersion = ref(state.configs.find(c => c.status === 'draft')?.version || state.configs[0]?.version || '');
const firstId = ref(state.evaluations[0]?.id || ''); const secondId = ref(state.evaluations[1]?.id || '');
const first = computed(() => state.evaluations.find(e => e.id === firstId.value)); const second = computed(() => state.evaluations.find(e => e.id === secondId.value));
const selected = computed(() => state.evaluations.find(e => e.id === route.params.id));
const form = ref<EvalCase>({ id: '', name: '', preference: '', expected: '' });
const judge = computed(() => state.models.some(m => m.role === '评估模型' && m.enabled && m.verified));
const metrics = [ { key: 'relevance', label: '偏好相关性', unit: '/ 5', source: '模型评分 · 固定示例', higher: true }, { key: 'faithfulness', label: '事实忠实度', unit: '/ 5', source: '模型评分 · 固定示例', higher: true }, { key: 'citations', label: '引用完整率', unit: '%', source: '规则评分 · 固定示例', higher: true }, { key: 'cost', label: '总费用', unit: 'USD', source: '用量汇总 · 固定示例', higher: false }, { key: 'latency', label: '平均耗时', unit: '秒', source: '运行事件 · 固定示例', higher: false } ];
function value(e: any, key: string) { const v = e?.[key]; return v === null || v === undefined ? '—' : Number(v).toFixed(key === 'cost' ? 2 : key === 'citations' ? 0 : 1); }
function delta(key: string) { const a = (first.value as any)?.[key]; const b = (second.value as any)?.[key]; if (a == null || b == null) return '尚无可比较结果'; const d = b - a; return d === 0 ? '无变化' : `${d > 0 ? '+' : ''}${d.toFixed(key === 'cost' ? 2 : 1)}`; }
function edit(item?: EvalCase) { form.value = item ? { ...item } : { id: '', name: '', preference: '', expected: '' }; error.value = ''; editing.value = true; }
async function save() { busy.value = 'case'; error.value = ''; try { await api.saveEvalCase({ ...form.value }); editing.value = false; notify('固定评估样例已保存。'); } catch (e) { error.value = (e as Error).message; } finally { busy.value = ''; } }
async function run() { busy.value = 'run'; error.value = ''; try { const id = await api.runEvaluation(configVersion.value); notify('示例评估已排队，未调用真实评估模型。'); router.push(`/evaluations/${id}`); } catch (e) { error.value = (e as Error).message; } finally { busy.value = ''; } }
</script>
<template>
  <template v-if="route.params.id"><RouterLink class="admin-back" to="/evaluations"><ArrowLeft :size="16" />全部评估实验</RouterLink><template v-if="selected"><header class="page-header"><div><div class="eyebrow">EVALUATION DETAIL · SYNTHETIC</div><h1>{{ selected.name }}</h1><p class="meta">{{ selected.configVersion }} · {{ selected.cases }} 个固定样例 · {{ formatDate(selected.createdAt) }}</p></div><Badge :status="selected.status" /></header>
      <p v-if="['running', 'queued'].includes(selected.status)" class="alert">示例评估正在推进。评分未返回时显示“—”，不会预填结果。</p><p v-if="selected.status === 'failed'" class="alert alert--danger">示例实验失败，尚未产生可用评分。请检查评估模型与当前场景后重新发起实验。</p>
      <div class="metric-grid"><div v-for="metric in metrics.slice(0, 4)" :key="metric.key" class="metric"><span class="meta">{{ metric.label }}</span><strong>{{ value(selected, metric.key) }} <small>{{ metric.unit }}</small></strong><span class="meta">{{ metric.source }}</span></div></div>
      <section class="card admin-section"><h2>评分来源与解读</h2><p class="muted">相关性与忠实度采用 1–5 分量表；引用完整率检查条目是否包含可追溯来源。所有数值为 synthetic 固定结果，尚未进行真实模型裁判或人工复核。</p><dl class="admin-kv"><dt>实验配置</dt><dd>{{ selected.configVersion }}</dd><dt>平均耗时</dt><dd>{{ value(selected, 'latency') }} 秒（示例）</dd><dt>人工复核</dt><dd>未进行</dd><dt>样例快照</dt><dd>{{ selected.cases }} 个样例；当前原型仅显示样例定义，逐项执行证据将在后端阶段实现。</dd></dl></section>
      <section class="card admin-section"><div class="section-heading"><h2>固定样例定义</h2><RouterLink to="/evaluations">返回管理</RouterLink></div><ul class="admin-list"><li v-for="item in state.evalCases.slice(0, selected.cases)" :key="item.id"><h3>{{ item.name }}</h3><p class="meta">偏好：{{ item.preference }}</p><p class="muted">验收：{{ item.expected }}</p></li></ul></section>
    </template><EmptyState v-else title="找不到这个实验" description="示例可能已经重置，请返回实验列表。"><RouterLink class="button" to="/evaluations">返回评估</RouterLink></EmptyState></template>
  <template v-else><header class="page-header"><div><div class="eyebrow">EVALUATION LAB</div><h1>每次调整，都有参照</h1><p class="muted">固定样例、相同尺度，比较配置改变带来的影响。</p></div><span class="chip"><FlaskConical :size="14" />synthetic 实验</span></header>
    <nav class="tabs" aria-label="评估视图"><button class="button button--ghost" :class="{ 'chip--active': tab === 'experiments' }" :aria-pressed="tab === 'experiments'" @click="tab = 'experiments'">实验记录</button><button class="button button--ghost" :class="{ 'chip--active': tab === 'compare' }" :aria-pressed="tab === 'compare'" @click="tab = 'compare'">A / B 对比</button><button class="button button--ghost" :class="{ 'chip--active': tab === 'cases' }" :aria-pressed="tab === 'cases'" @click="tab = 'cases'">固定样例 <span class="meta">{{ state.evalCases.length }}</span></button></nav>
    <p v-if="error && !editing" class="alert alert--danger" role="alert">{{ error }}</p>
    <template v-if="tab === 'experiments'"><section class="card"><div class="section-heading"><h2>运行一次实验</h2><span class="meta">使用 {{ state.evalCases.length }} 个当前样例</span></div><div class="admin-toolbar"><label class="field">待评估配置<select v-model="configVersion" class="field-control"><option value="" disabled>选择配置版本</option><option v-for="config in state.configs" :key="config.id" :value="config.version">{{ config.version }} · {{ config.name }} · {{ config.status === 'draft' ? '草稿' : '已发布' }}</option></select></label><button class="button button--primary" :disabled="!!busy || !configVersion || !state.evalCases.length || !judge" @click="run"><Play :size="16" />{{ busy === 'run' ? '正在创建…' : '运行模拟评估' }}</button></div><p v-if="!judge" class="alert">尚无可用的评估模型。请在<RouterLink to="/models">模型与连接</RouterLink>中启用“评估模型”并完成模拟连接测试。</p><p class="admin-note">评估会创建独立实验记录；不会发布 Agent 草稿。</p></section>
      <EmptyState v-if="!state.evaluations.length" title="还没有评估实验" description="准备固定样例并配置评估模型，运行第一组实验。" />
      <template v-else><div class="section-heading admin-section"><h2>实验记录</h2><button class="button button--ghost" @click="tab = 'compare'">比较结果 <ArrowRight :size="16" /></button></div><p class="admin-scroll-hint">表格可左右滚动。</p><div class="table-wrap"><table class="data-table admin-table"><thead><tr><th>实验</th><th>配置 / 样例</th><th>状态</th><th>相关性 / 忠实度</th><th>引用</th><th>示例费用</th></tr></thead><tbody><tr v-for="item in state.evaluations" :key="item.id"><td class="wide-cell"><RouterLink :to="`/evaluations/${item.id}`">{{ item.name }}</RouterLink><small>{{ formatDate(item.createdAt) }}</small></td><td>{{ item.configVersion }}<small>{{ item.cases }} 个样例</small></td><td><Badge :status="item.status" /></td><td class="nowrap">{{ value(item, 'relevance') }} / {{ value(item, 'faithfulness') }}<small>模型评分示例 · 满分 5</small></td><td>{{ value(item, 'citations') }}%</td><td>${{ value(item, 'cost') }}</td></tr></tbody></table></div></template>
    </template>
    <template v-else-if="tab === 'compare'"><section class="card"><div class="section-heading"><h2>选择两次实验</h2><span class="meta">B 相对 A 的变化</span></div><div class="form-grid"><label class="field">实验 A · 基线<select v-model="firstId" class="field-control"><option value="" disabled>选择实验</option><option v-for="item in state.evaluations" :key="item.id" :value="item.id">{{ item.name }} · {{ item.configVersion }}</option></select></label><label class="field">实验 B · 对照<select v-model="secondId" class="field-control"><option value="" disabled>选择实验</option><option v-for="item in state.evaluations" :key="item.id" :value="item.id">{{ item.name }} · {{ item.configVersion }}</option></select></label></div><p class="admin-note">必须选取使用相同样例的实验。原型样例数量一致不等于真实实验输入相同，正式实现将校验数据集版本。</p></section>
      <EmptyState v-if="!first || !second" title="选择两个实验开始比较" description="先完成至少两次评估，才能查看配置差异。" /><p v-else-if="firstId === secondId" class="alert admin-section">请选择两次不同的实验。</p><template v-else><p v-if="first.cases !== second.cases" class="alert admin-section">这两次实验的样例数量不同，数值不可直接归因于配置变化。</p><p class="admin-scroll-hint">对比表可左右滚动。</p><div class="table-wrap admin-section"><table class="data-table admin-table"><thead><tr><th>指标与来源</th><th>A · {{ first.configVersion }}</th><th>B · {{ second.configVersion }}</th><th>变化</th></tr></thead><tbody><tr v-for="metric in metrics" :key="metric.key"><td>{{ metric.label }}<small>{{ metric.source }}</small></td><td class="nowrap">{{ value(first, metric.key) }} {{ metric.unit }}</td><td class="nowrap">{{ value(second, metric.key) }} {{ metric.unit }}</td><td>{{ delta(metric.key) }}<small>{{ metric.higher ? '越高越好' : '越低越好' }}</small></td></tr></tbody></table></div><p class="meta">小样本演示只用于审阅交互，不能据此宣称统计显著或质量提升。</p></template>
    </template>
    <template v-else><div class="section-heading"><h2>固定样例集</h2><button class="button button--primary" @click="edit()"><Plus :size="16" />添加样例</button></div><EmptyState v-if="!state.evalCases.length" title="还没有评估样例" description="用用户偏好和预期行为定义可重复的检查。" /><section v-else class="card"><ul class="admin-list"><li v-for="item in state.evalCases" :key="item.id"><div class="section-heading"><h3>{{ item.name }}</h3><button class="button button--ghost" @click="edit(item)">编辑</button></div><p class="muted">偏好：{{ item.preference }}</p><p class="meta">预期：{{ item.expected }}</p></li></ul></section></template>
  </template>
  <Modal :open="editing" :title="form.id ? '编辑固定样例' : '添加固定样例'" @close="editing = false"><form id="case-form" class="admin-form stack" @submit.prevent="save"><p v-if="error" class="alert alert--danger" role="alert">{{ error }}</p><label class="field">样例名称<input v-model="form.name" class="field-control" required maxlength="80"></label><label class="field">用户偏好输入<textarea v-model="form.preference" class="field-control" required maxlength="2000" placeholder="关注主题、包含与排除词、时间窗口…"></textarea></label><label class="field">预期行为与检查标准<textarea v-model="form.expected" class="field-control" required maxlength="2000" placeholder="应包含/排除哪些内容，引用及异常恢复应如何表现…"></textarea></label></form><template #footer><button class="button" :disabled="busy === 'case'" @click="editing = false">取消</button><button class="button button--primary" form="case-form" type="submit" :disabled="busy === 'case'">{{ busy === 'case' ? '正在保存…' : '保存样例' }}</button></template></Modal>
</template>
