<script setup lang="ts">
import { computed, ref } from 'vue';
import { RefreshCw } from 'lucide-vue-next';
import { state, api, notify, formatDate } from '@shared/mock';
import Badge from '@shared/Badge.vue';
import EmptyState from '@shared/EmptyState.vue';
const filter = ref('all'); const busy = ref(''); const error = ref('');
const deliveries = computed(() => state.deliveries.filter(d => filter.value === 'all' || d.status === filter.value));
async function retry(id: string) { busy.value = id; error.value = ''; try { await api.retryDelivery(id); notify('模拟重试已提交，同一份简报内容保持不变；没有发送真实邮件。'); } catch (e) { error.value = (e as Error).message; } finally { busy.value = ''; } }
</script>
<template><header class="page-header"><div><div class="eyebrow">DELIVERY OPERATIONS</div><h1>投递记录</h1><p class="muted">内容已生成，与邮件已送达，是两件不同的事。</p></div></header><p class="alert">全部投递为 synthetic 示例。“已提交发送”表示示例服务接受请求，不表示收件人已收到。</p><p v-if="error" class="alert alert--danger" role="alert">{{ error }}</p><div class="admin-toolbar admin-section"><label class="field">投递状态<select v-model="filter" class="field-control"><option value="all">全部状态</option><option value="failed">失败</option><option value="unknown">状态未知</option><option value="pending">待提交</option><option value="submitted">已提交发送</option></select></label></div><EmptyState v-if="!deliveries.length" title="没有匹配的投递记录" description="站内简报的生成记录与外部邮件记录分别保存。" /><template v-else><p class="admin-scroll-hint">表格可左右滚动，失败原因保留在对应记录中。</p><div class="table-wrap"><table class="data-table admin-table"><thead><tr><th>收件用户 / 目的地</th><th>简报</th><th>状态</th><th>最近尝试</th><th>结果与操作</th></tr></thead><tbody><tr v-for="item in deliveries" :key="item.id"><td class="wide-cell"><strong>{{ item.userName }}</strong><small>{{ item.destination }}</small><small>{{ item.channel === 'email' ? '电子邮件' : '站内' }}</small></td><td class="mono nowrap">{{ item.briefId }}</td><td><Badge :status="item.status" /></td><td class="nowrap">{{ formatDate(item.time) }}<small>已尝试 {{ item.attempts }} 次</small></td><td class="wide-cell"><p class="meta">{{ item.error || (item.status === 'submitted' ? '示例服务已接受请求，送达回执未知。' : '等待投递状态更新。') }}</p><button v-if="item.status === 'failed'" class="button" :disabled="!!busy" @click="retry(item.id)"><RefreshCw :size="15" />{{ busy === item.id ? '正在重试…' : '重试同一份简报' }}</button><span v-if="item.status === 'unknown'" class="meta">确认外部结果后再重试，避免重复投递。</span></td></tr></tbody></table></div></template></template>
