// Generated by scripts/frontend/generate-contract.mjs. Do not edit.
// Source: docs/releases/v1.0.0/implementation/backend/h001/contracts/openapi.json
// SHA-256: 329f6336ee048922f9619dcbe462271cf8544daa3cef036a0e58bace3502402c
// Structural TypeScript types; input lengths/ranges and cross-field constraints remain server-validated.

export type RunStatus = "queued" | "running" | "completed" | "partial" | "failed" | "cancelling" | "cancelled";

export type DeliveryStatus = "disabled" | "pending" | "submitted" | "failed" | "unknown";

export type Preferences = {
  /** 服务端版本，0 表示尚未配置；提交时原样回传作并发校验，成功保存由服务端递增。 */
  "version": number;
  /** 关注背景/职业说明，并非鉴权角色。 */
  "role": string;
  "topics": Array<string>;
  "keywords": Array<string>;
};

export type DeliverySettings = {
  /** 每日站内自动推送时间，按系统时区 Asia/Shanghai 解释。 */
  "time": string;
};

export type Citation = {
  "id": string;
  "name": string;
  "title": string;
  "url": string;
  "publishedAt": string | null;
};

export type NewsItem = {
  "id": string;
  "title": string;
  "summary": string;
  "reason": string;
  "topic": string;
  "source": string;
  "sourceType": "rss" | "newsnow" | "search";
  "publishedAt": string | null;
  "url": string;
  "citations": Array<Citation>;
  /** 实际采集或搜索取得证据的时刻；绝不能代替 publishedAt。 */
  "fetchedAt": string;
  /** 不可变来源或搜索证据快照的公开不透明标识，不是宿主路径或运行标识。 */
  "snapshotId": string;
};

export type Brief = {
  "id": string;
  "title": string;
  "date": string;
  "version": number;
  "summary": string;
  "items": Array<NewsItem>;
  "generationStatus": RunStatus;
  "deliveryStatus": DeliveryStatus;
  "generatedAt": string;
  /** 未取得有效证据的来源名称；部分完成时向读者明确缺失。 */
  "missingSources": Array<string>;
};

export type RunEvent = {
  "id": number;
  /** 完整 RFC 3339 实际事件时间，服务端持久化为 UTC；页面可格式化为本地短时间。 */
  "time": string;
  "title": string;
  "detail": string;
  "status": string;
  "duration": string;
  "tool"?: string;
  /** 脱敏、有界参数文本；不是凭据或私有思维链。 */
  "params"?: string;
  /** 有界结果/错误摘要。 */
  "output"?: string;
};

export type Subtask = {
  "id": string;
  "name": string;
  "status": RunStatus;
  "detail": string;
};

export type AgentRun = {
  "id": string;
  "userName": string;
  "status": RunStatus;
  "model": string;
  "configVersion": string;
  "startedAt": string;
  "elapsedSeconds": number;
  /** 提供商实际报告的输入 token 数，未知为 null。 */
  "inputTokens": number | null;
  /** 提供商实际报告的输出 token 数，未知为 null。 */
  "outputTokens": number | null;
  /** 按已配置价格估算的美元金额；真实用量或价格不可用时为 null。 */
  "cost": number | null;
  "searchCount": number;
  "events": Array<RunEvent>;
  "subtasks": Array<Subtask>;
};

export type Source = {
  "id": string;
  "name": string;
  "kind": "rss" | "newsnow";
  "sourceId": string;
  "url": string;
  /** 有效轮询周期，单位秒；界面可以换算为分钟显示。 */
  "interval": number;
  /** NewsNow 上游配置周期，单位秒；RSS 未提供时为 0。 */
  "upstreamInterval": number;
  "status": "healthy" | "syncing" | "failed" | "disabled" | "unverified";
  /** RFC 3339 UTC 时间；原型未知/尚未发生时为空串。不得将空值显示为成功。 */
  "lastSuccess": ((string) | (""));
  /** RFC 3339 UTC 时间；原型未知/尚未发生时为空串。不得将空值显示为成功。 */
  "nextFetch": ((string) | (""));
  /** RFC 3339 UTC 时间；原型未知/尚未发生时为空串。不得将空值显示为成功。 */
  "lastChanged": ((string) | (""));
  "items": number;
  "error": string;
  /** 当前有效不可变快照 ID；无有效快照为 null。失败或304保留原值。 */
  "snapshotId": string | null;
  /** 当前快照原始数据实际取得时刻；304或失败不能更新成新的内容采集时间。 */
  "snapshotFetchedAt": string | null;
  /** 最近一次实际HTTP采集尝试时刻（含失败/304），不代表发布成功。 */
  "lastFetchedAt": string | null;
  /** 当前时间减snapshotFetchedAt；无有效快照为null。 */
  "cacheAgeSeconds": number | null;
  /** 无快照或缓存超过有效周期时为true；响应为304可延期有效性但不伪造快照年龄。 */
  "stale": boolean;
  /** NewsNow上游周期配置来源提交或内容指纹；RSS或没有可信元数据为null。 */
  "upstreamRevision": string | null;
};

export type ModelConfig = {
  "id": string;
  "name": string;
  "provider": string;
  "modelId": string;
  "endpoint": string;
  /** 固定遮罩/后缀标识，绝不返回原始 API key。 */
  "keyMasked": string;
  "role": "主模型" | "摘要模型" | "评估模型" | "子模型";
  "enabled": boolean;
  "verified": boolean;
  "contextWindow": number;
};

export type AgentConfig = {
  "id": string;
  "name": string;
  "version": string;
  "status": "published" | "draft";
  "modelId": string;
  "summaryModelId": string;
  "maxModelCalls": number;
  "maxToolCalls": number;
  "maxSeconds": number;
  "summaryTokens": number;
  "summaryMessages": number;
  "summaryRatio": number;
  "subagentConcurrency": number;
  "tools": Array<"list_dir" | "read_file" | "search_content" | "write_file" | "bash" | "web_search" | "delegate_research">;
  "systemPrompt": string;
};

export type EvalCase = {
  "id": string;
  "name": string;
  "preference": string;
  "expected": string;
  "preferenceSnapshot": Preferences;
  /** 评估的新鲜度判定时钟；省略时在保存用例时由服务器固定，后续实验不能使用当前时钟替换。 */
  "fixedAt": string;
  /** 固定来源快照标识；省略时保存用例时捕获当前可用快照。显式空数组是无证据测试用例，不能偷偷查询实时网络。 */
  "sourceSnapshotIds": Array<string>;
  /** 每次保存递增；实验绑定该修订，后续修改不影响已创建实验。 */
  "revision": number;
};

export type Evaluation = {
  "id": string;
  "name": string;
  "configVersion": string;
  "status": "queued" | "running" | "completed" | "failed";
  /** 0–5，明确标记模型评分；未评分为 null。 */
  "relevance": number | null;
  /** 0–5，明确标记模型评分；未评分为 null。 */
  "faithfulness": number | null;
  /** 0–100%，固定评估样本的引用规则检查结果，不代表模型整体准确率。 */
  "citations": number | null;
  "cost": number | null;
  /** 秒。 */
  "latency": number | null;
  "cases": number;
  "createdAt": string;
  /** 固定用例修订与来源快照清单的内容指纹；同一标识表示相同输入集合。 */
  "datasetVersion": string;
  /** 规则实现与人工/LLM评分器配置的不可变版本标识。 */
  "scorerVersion": string;
  /** 实验实际使用的模型配置 ID；由所选已发布配置绑定。 */
  "modelId": string;
  /** 逐用例和逐指标结果；未执行的指标不伪造分数，聚合值只统计可用项。 */
  "results": Array<EvaluationCaseResult>;
};

export type Delivery = {
  "id": string;
  "briefId": string;
  "userName": string;
  /** 站内简报位置，不包含邮件地址。 */
  "destination": string;
  "channel": "in_app";
  "status": DeliveryStatus;
  "attempts": number;
  "time": string;
  "error": string;
};

export type Memory = {
  "id": string;
  "text": string;
  "source": string;
  "updatedAt": string;
};

export type Session = {
  "kind": "anonymous";
  "userId": string;
  "name": string;
  "onboardingCompleted": boolean;
};

export type Error = {
  "code": "VALIDATION_ERROR" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "VERSION_CONFLICT" | "INVALID_STATE" | "SECRET_REQUIRED" | "SOURCE_INTERVAL_TOO_SHORT" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR" | "ACCOUNT_BLOCKED" | "CSRF_REJECTED";
  "message": string;
  "requestId": string;
  "fields"?: {
    [key: string]: string;
  };
};

export type AcceptedEvaluation = {
  "evaluationId": string;
};

export type SourceWrite = {
  "name": string;
  "kind": "rss" | "newsnow";
  "sourceId": string;
  "url": string;
  /** 有效轮询周期，单位秒。 */
  "interval": number;
};

export type ModelWrite = {
  "name": string;
  "provider": string;
  "modelId": string;
  "endpoint": string;
  "role": "主模型" | "摘要模型" | "评估模型" | "子模型";
  "contextWindow": number;
  /** 可选；缺省保留旧 key，非空值创建或替换；撤销使用独立 DELETE。 */
  "apiKey"?: string;
};

export type ConfigWrite = {
  "name": string;
  "modelId": string;
  "summaryModelId": string;
  "maxModelCalls": number;
  "maxToolCalls": number;
  "maxSeconds": number;
  "summaryTokens": number;
  "summaryMessages": number;
  "summaryRatio": number;
  "subagentConcurrency": number;
  "tools": Array<"list_dir" | "read_file" | "search_content" | "write_file" | "bash" | "web_search" | "delegate_research">;
  "systemPrompt": string;
};

export type EvalCaseWrite = {
  "name": string;
  "preference": string;
  "expected": string;
  "preferenceSnapshot"?: Preferences;
  /** 评估的新鲜度判定时钟；省略时在保存用例时由服务器固定，后续实验不能使用当前时钟替换。 */
  "fixedAt"?: string;
  /** 固定来源快照标识；省略时保存用例时捕获当前可用快照。显式空数组是无证据测试用例，不能偷偷查询实时网络。 */
  "sourceSnapshotIds"?: Array<string>;
};

export type DeliverySettingsWrite = {
  /** 每日站内自动推送时间，按系统时区 Asia/Shanghai 解释。 */
  "time": string;
};

export type EnabledWrite = {
  "enabled": boolean;
};

export type GenerateBriefRequest = {
  "preferenceVersion": number;
};

export type EvaluationRequest = {
  "configVersion": string;
};

export type ConnectionTest = {
  "verified": boolean;
  "message": string;
  "testedAt": string;
  "capabilities": Array<string>;
};

export type HealthSummary = {
  "activeRuns": number;
  "failedSources": number;
  "failedDeliveries": number;
  "sampleCount": number;
  "completionRate": number | null;
  "generatedAt": string;
};

export type BriefPage = {
  "items": Array<Brief>;
  "nextCursor": string | null;
};

export type AgentRunPage = {
  "items": Array<AgentRun>;
  "nextCursor": string | null;
};

export type MemoryPage = {
  "items": Array<Memory>;
  "nextCursor": string | null;
};

export type SourcePage = {
  "items": Array<Source>;
  "nextCursor": string | null;
};

export type ModelConfigPage = {
  "items": Array<ModelConfig>;
  "nextCursor": string | null;
};

export type AgentConfigPage = {
  "items": Array<AgentConfig>;
  "nextCursor": string | null;
};

export type EvalCasePage = {
  "items": Array<EvalCase>;
  "nextCursor": string | null;
};

export type EvaluationPage = {
  "items": Array<Evaluation>;
  "nextCursor": string | null;
};

export type DeliveryPage = {
  "items": Array<Delivery>;
  "nextCursor": string | null;
};

export type PreferencesWrite = ({
  /** 服务端版本，0 表示尚未配置；提交时原样回传作并发校验，成功保存由服务端递增。 */
  "version": number;
  /** 关注背景/职业说明，并非鉴权角色。 */
  "role": string;
  "topics": Array<string>;
  "keywords": Array<string>;
}) & (({
  "topics"?: unknown;
  [key: string]: unknown;
}) | ({
  "keywords"?: unknown;
  [key: string]: unknown;
}));

export type AdminSession = {
  "kind": "admin";
  "userId": string;
  "name": string;
};

export type AdminLoginRequest = {
  "email": string;
  "password": string;
};

export type GenerationProgress = {
  "id": string;
  "status": RunStatus;
  /** 可估计时为0..100；null时展示不定进度。成功发布前不能显示100。 */
  "percent": number | null;
  /** 服务端估计的剩余秒数，可随负载更新；null表示暂不能估计。不是完成承诺。 */
  "remainingSeconds": number | null;
  "updatedAt": string;
  "briefId": string | null;
  "error": string;
};

export type AnonymousAccount = {
  "id": string;
  "name": string;
  "createdAt": string;
  "lastSeenAt": string;
  "status": "active" | "blocked";
  "risk": "normal" | "watch" | "high";
  "requestsLastMinute": number;
  "generationsToday": number;
  "rateLimitHits": number;
  "activeGenerations": number;
  /** 脱敏来源标签，不返回原始IP或会话token。 */
  "ipLabel": string;
  "blockReason": string;
};

export type AbuseEvent = {
  "id": string;
  "accountId": string;
  "time": string;
  "kind": "rate_limited" | "account_blocked" | "account_unblocked" | "generation_rejected";
  "detail": string;
};

export type AnonymousPolicy = {
  "requestsPerMinute": number;
  "generationsPerDay": number;
  "maxConcurrentGenerations": number;
  "accountsPerIpHour": number;
};

export type AnonymousAccountStatusWrite = {
  "status": "active" | "blocked";
  "reason": string;
};

export type AnonymousAccountPage = {
  "items": Array<AnonymousAccount>;
  "nextCursor": string | null;
};

export type AbuseEventPage = {
  "items": Array<AbuseEvent>;
  "nextCursor": string | null;
};

export type AdminBrief = {
  "id": string;
  "title": string;
  "date": string;
  "version": number;
  "summary": string;
  "items": Array<NewsItem>;
  "generationStatus": RunStatus;
  "deliveryStatus": DeliveryStatus;
  "generatedAt": string;
  "runId": string;
  "preferenceSnapshot": Preferences;
  /** 未取得有效证据的来源名称；部分完成时向读者明确缺失。 */
  "missingSources": Array<string>;
};

export type EvaluationScore = {
  "metric": "relevance" | "faithfulness" | "freshness" | "deduplication" | "sourceCoverage" | "citationAccuracy" | "latency" | "cost";
  "method": "rule" | "human" | "llm";
  "value": number | null;
  "maximum": number | null;
  /** 规则判定适用时给出布尔值；无评分/评分器失败为 null。 */
  "passed": boolean | null;
  /** 评分失败的简短脱敏原因；未失败为空串。 */
  "error": string;
};

export type EvaluationCaseResult = {
  "caseId": string;
  "caseRevision": number;
  "status": "queued" | "running" | "completed" | "failed";
  "scores": Array<EvaluationScore>;
};

export type components = {
  schemas: {
    "RunStatus": RunStatus;
    "DeliveryStatus": DeliveryStatus;
    "Preferences": Preferences;
    "DeliverySettings": DeliverySettings;
    "Citation": Citation;
    "NewsItem": NewsItem;
    "Brief": Brief;
    "RunEvent": RunEvent;
    "Subtask": Subtask;
    "AgentRun": AgentRun;
    "Source": Source;
    "ModelConfig": ModelConfig;
    "AgentConfig": AgentConfig;
    "EvalCase": EvalCase;
    "Evaluation": Evaluation;
    "Delivery": Delivery;
    "Memory": Memory;
    "Session": Session;
    "Error": Error;
    "AcceptedEvaluation": AcceptedEvaluation;
    "SourceWrite": SourceWrite;
    "ModelWrite": ModelWrite;
    "ConfigWrite": ConfigWrite;
    "EvalCaseWrite": EvalCaseWrite;
    "DeliverySettingsWrite": DeliverySettingsWrite;
    "EnabledWrite": EnabledWrite;
    "GenerateBriefRequest": GenerateBriefRequest;
    "EvaluationRequest": EvaluationRequest;
    "ConnectionTest": ConnectionTest;
    "HealthSummary": HealthSummary;
    "BriefPage": BriefPage;
    "AgentRunPage": AgentRunPage;
    "MemoryPage": MemoryPage;
    "SourcePage": SourcePage;
    "ModelConfigPage": ModelConfigPage;
    "AgentConfigPage": AgentConfigPage;
    "EvalCasePage": EvalCasePage;
    "EvaluationPage": EvaluationPage;
    "DeliveryPage": DeliveryPage;
    "PreferencesWrite": PreferencesWrite;
    "AdminSession": AdminSession;
    "AdminLoginRequest": AdminLoginRequest;
    "GenerationProgress": GenerationProgress;
    "AnonymousAccount": AnonymousAccount;
    "AbuseEvent": AbuseEvent;
    "AnonymousPolicy": AnonymousPolicy;
    "AnonymousAccountStatusWrite": AnonymousAccountStatusWrite;
    "AnonymousAccountPage": AnonymousAccountPage;
    "AbuseEventPage": AbuseEventPage;
    "AdminBrief": AdminBrief;
    "EvaluationScore": EvaluationScore;
    "EvaluationCaseResult": EvaluationCaseResult;
  };
};

export const contractSource = "docs/releases/v1.0.0/implementation/backend/h001/contracts/openapi.json";
export const contractSha256 = "329f6336ee048922f9619dcbe462271cf8544daa3cef036a0e58bace3502402c";
export const operationMetadata = {
  "getSession": {
    "method": "GET",
    "path": "/auth/session",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getPreferences": {
    "method": "GET",
    "path": "/me/preferences",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "savePreferences": {
    "method": "PUT",
    "path": "/me/preferences",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getDeliverySettings": {
    "method": "GET",
    "path": "/me/delivery-settings",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "saveDeliverySettings": {
    "method": "PUT",
    "path": "/me/delivery-settings",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listMemories": {
    "method": "GET",
    "path": "/me/memories",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "deleteMemory": {
    "method": "DELETE",
    "path": "/me/memories/{id}",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      204
    ],
    "stream": false
  },
  "listBriefs": {
    "method": "GET",
    "path": "/me/briefs",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit",
      "date",
      "topic",
      "status",
      "q"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "generateBrief": {
    "method": "POST",
    "path": "/me/briefs",
    "role": "authenticated",
    "idempotencyRequired": true,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "getBrief": {
    "method": "GET",
    "path": "/me/briefs/{id}",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listOwnDeliveries": {
    "method": "GET",
    "path": "/me/deliveries",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "retryOwnDelivery": {
    "method": "POST",
    "path": "/me/deliveries/{id}/retry",
    "role": "authenticated",
    "idempotencyRequired": true,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "getOverview": {
    "method": "GET",
    "path": "/admin/overview",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listSources": {
    "method": "GET",
    "path": "/admin/sources",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "createSource": {
    "method": "POST",
    "path": "/admin/sources",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      201
    ],
    "stream": false
  },
  "saveSource": {
    "method": "PUT",
    "path": "/admin/sources/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getSource": {
    "method": "GET",
    "path": "/admin/sources/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listModels": {
    "method": "GET",
    "path": "/admin/models",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "createModel": {
    "method": "POST",
    "path": "/admin/models",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      201
    ],
    "stream": false
  },
  "saveModel": {
    "method": "PUT",
    "path": "/admin/models/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listConfigs": {
    "method": "GET",
    "path": "/admin/agent-configs",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "createConfig": {
    "method": "POST",
    "path": "/admin/agent-configs",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      201
    ],
    "stream": false
  },
  "saveConfig": {
    "method": "PUT",
    "path": "/admin/agent-configs/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listEvalCases": {
    "method": "GET",
    "path": "/admin/eval-cases",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "createEvalCase": {
    "method": "POST",
    "path": "/admin/eval-cases",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      201
    ],
    "stream": false
  },
  "saveEvalCase": {
    "method": "PUT",
    "path": "/admin/eval-cases/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "setSourceEnabled": {
    "method": "PUT",
    "path": "/admin/sources/{id}/enabled",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "fetchSource": {
    "method": "POST",
    "path": "/admin/sources/{id}/fetch",
    "role": "admin",
    "idempotencyRequired": true,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "setModelEnabled": {
    "method": "PUT",
    "path": "/admin/models/{id}/enabled",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "testModel": {
    "method": "POST",
    "path": "/admin/models/{id}/test",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "revokeModelSecret": {
    "method": "DELETE",
    "path": "/admin/models/{id}/secret",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      204
    ],
    "stream": false
  },
  "publishConfig": {
    "method": "POST",
    "path": "/admin/agent-configs/{id}/publish",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listAdminRuns": {
    "method": "GET",
    "path": "/admin/runs",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit",
      "status",
      "model",
      "from",
      "to"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getAdminRun": {
    "method": "GET",
    "path": "/admin/runs/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "cancelAdminRun": {
    "method": "POST",
    "path": "/admin/runs/{id}/cancel",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "listEvaluations": {
    "method": "GET",
    "path": "/admin/evaluations",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "runEvaluation": {
    "method": "POST",
    "path": "/admin/evaluations",
    "role": "admin",
    "idempotencyRequired": true,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "getEvaluation": {
    "method": "GET",
    "path": "/admin/evaluations/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listAdminDeliveries": {
    "method": "GET",
    "path": "/admin/deliveries",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "retryAdminDelivery": {
    "method": "POST",
    "path": "/admin/deliveries/{id}/retry",
    "role": "admin",
    "idempotencyRequired": true,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "adminRunEvents": {
    "method": "GET",
    "path": "/admin/runs/{id}/events",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": true
  },
  "ensureAnonymousSession": {
    "method": "POST",
    "path": "/auth/anonymous",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "adminLogin": {
    "method": "POST",
    "path": "/admin/auth/login",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getAdminSession": {
    "method": "GET",
    "path": "/admin/auth/session",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "adminLogout": {
    "method": "DELETE",
    "path": "/admin/auth/session",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      204
    ],
    "stream": false
  },
  "getGenerationProgress": {
    "method": "GET",
    "path": "/me/generations/{id}",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "cancelGeneration": {
    "method": "POST",
    "path": "/me/generations/{id}/cancel",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "listAnonymousAccounts": {
    "method": "GET",
    "path": "/admin/anonymous-accounts",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "setAnonymousAccountStatus": {
    "method": "PUT",
    "path": "/admin/anonymous-accounts/{id}/status",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listAbuseEvents": {
    "method": "GET",
    "path": "/admin/abuse-events",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getAnonymousPolicy": {
    "method": "GET",
    "path": "/admin/anonymous-policy",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "saveAnonymousPolicy": {
    "method": "PUT",
    "path": "/admin/anonymous-policy",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getCurrentGeneration": {
    "method": "GET",
    "path": "/me/generations/current",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  }
} as const;
export type OperationId = keyof typeof operationMetadata;
export type OperationRequests = {
  "getSession": undefined;
  "getPreferences": undefined;
  "savePreferences": PreferencesWrite;
  "getDeliverySettings": undefined;
  "saveDeliverySettings": DeliverySettingsWrite;
  "listMemories": undefined;
  "deleteMemory": undefined;
  "listBriefs": undefined;
  "generateBrief": GenerateBriefRequest;
  "getBrief": undefined;
  "listOwnDeliveries": undefined;
  "retryOwnDelivery": undefined;
  "getOverview": undefined;
  "listSources": undefined;
  "createSource": SourceWrite;
  "saveSource": SourceWrite;
  "getSource": undefined;
  "listModels": undefined;
  "createModel": ModelWrite;
  "saveModel": ModelWrite;
  "listConfigs": undefined;
  "createConfig": ConfigWrite;
  "saveConfig": ConfigWrite;
  "listEvalCases": undefined;
  "createEvalCase": EvalCaseWrite;
  "saveEvalCase": EvalCaseWrite;
  "setSourceEnabled": EnabledWrite;
  "fetchSource": undefined;
  "setModelEnabled": EnabledWrite;
  "testModel": undefined;
  "revokeModelSecret": undefined;
  "publishConfig": undefined;
  "listAdminRuns": undefined;
  "getAdminRun": undefined;
  "cancelAdminRun": undefined;
  "listEvaluations": undefined;
  "runEvaluation": EvaluationRequest;
  "getEvaluation": undefined;
  "listAdminDeliveries": undefined;
  "retryAdminDelivery": undefined;
  "adminRunEvents": undefined;
  "ensureAnonymousSession": undefined;
  "adminLogin": AdminLoginRequest;
  "getAdminSession": undefined;
  "adminLogout": undefined;
  "getGenerationProgress": undefined;
  "cancelGeneration": undefined;
  "listAnonymousAccounts": undefined;
  "setAnonymousAccountStatus": AnonymousAccountStatusWrite;
  "listAbuseEvents": undefined;
  "getAnonymousPolicy": undefined;
  "saveAnonymousPolicy": AnonymousPolicy;
  "getCurrentGeneration": undefined;
};
export type OperationResponses = {
  "getSession": Session;
  "getPreferences": Preferences;
  "savePreferences": Preferences;
  "getDeliverySettings": DeliverySettings;
  "saveDeliverySettings": DeliverySettings;
  "listMemories": MemoryPage;
  "deleteMemory": undefined;
  "listBriefs": BriefPage;
  "generateBrief": GenerationProgress;
  "getBrief": Brief;
  "listOwnDeliveries": DeliveryPage;
  "retryOwnDelivery": Delivery;
  "getOverview": HealthSummary;
  "listSources": SourcePage;
  "createSource": Source;
  "saveSource": Source;
  "getSource": Source;
  "listModels": ModelConfigPage;
  "createModel": ModelConfig;
  "saveModel": ModelConfig;
  "listConfigs": AgentConfigPage;
  "createConfig": AgentConfig;
  "saveConfig": AgentConfig;
  "listEvalCases": EvalCasePage;
  "createEvalCase": EvalCase;
  "saveEvalCase": EvalCase;
  "setSourceEnabled": Source;
  "fetchSource": Source;
  "setModelEnabled": ModelConfig;
  "testModel": ConnectionTest;
  "revokeModelSecret": undefined;
  "publishConfig": AgentConfig;
  "listAdminRuns": AgentRunPage;
  "getAdminRun": AgentRun;
  "cancelAdminRun": AgentRun;
  "listEvaluations": EvaluationPage;
  "runEvaluation": AcceptedEvaluation;
  "getEvaluation": Evaluation;
  "listAdminDeliveries": DeliveryPage;
  "retryAdminDelivery": Delivery;
  "adminRunEvents": RunEvent;
  "ensureAnonymousSession": Session;
  "adminLogin": AdminSession;
  "getAdminSession": AdminSession;
  "adminLogout": undefined;
  "getGenerationProgress": GenerationProgress;
  "cancelGeneration": GenerationProgress;
  "listAnonymousAccounts": AnonymousAccountPage;
  "setAnonymousAccountStatus": AnonymousAccount;
  "listAbuseEvents": AbuseEventPage;
  "getAnonymousPolicy": AnonymousPolicy;
  "saveAnonymousPolicy": AnonymousPolicy;
  "getCurrentGeneration": ((GenerationProgress) | (null));
};
