// Generated by scripts/frontend/generate-contract.mjs. Do not edit.
// Source: backend/src/zhigenews/contracts/openapi.json
// SHA-256: 49bc93aaca5623a0d5ea7a99349c1a2f41ac63b1210b1a33885bfaa677885c5c
// Structural TypeScript types; input lengths/ranges and cross-field constraints remain server-validated.

export type RunStatus = "queued" | "running" | "completed" | "partial" | "failed" | "cancelling" | "cancelled";

export type DeliveryStatus = "disabled" | "pending" | "submitted" | "failed" | "unknown";

export type Preferences = {
  /** 服务端版本，0 表示尚未配置；提交时原样回传作并发校验，成功保存由服务端递增。 */
  "version": number;
  /** 关注背景/职业说明，并非鉴权角色。 */
  "role": string;
  "topics": Array<string>;
  "keywords": Array<string>;
};

export type DeliverySettings = {
  /** 每日站内自动推送时间，按系统时区 Asia/Shanghai 解释。 */
  "time": string;
};

export type Citation = {
  "id": string;
  "name": string;
  "title": string;
  "url": string;
  "publishedAt": string | null;
};

export type NewsItem = {
  "id": string;
  "title": string;
  "summary": string;
  "topic": string;
  "source": string;
  /** 保留历史证据的原始来源类型；当前订阅采集仅支持 RSS，联网补充搜索使用 search。 */
  "sourceType": "rss" | "newsnow" | "search";
  "publishedAt": string | null;
  "url": string;
  /** 实际采集或搜索取得证据的时刻；绝不能代替 publishedAt。 */
  "fetchedAt": string;
  /** 不可变来源或搜索证据快照的公开不透明标识，不是宿主路径或运行标识。 */
  "snapshotId": string;
};

export type Brief = {
  "id": string;
  "title": string;
  "date": string;
  "version": number;
  "summary": string;
  "items": Array<NewsItem>;
  "generationStatus": RunStatus;
  "deliveryStatus": DeliveryStatus;
  "generatedAt": string;
};

export type RunEvent = {
  "id": number;
  /** 完整 RFC 3339 实际事件时间，服务端持久化为 UTC；页面可格式化为本地短时间。 */
  "time": string;
  "title": string;
  "detail": string;
  "status": string;
  "duration": string;
  "tool"?: string;
  /** 脱敏、有界参数文本；不是凭据或私有思维链。 */
  "params"?: string;
  /** 有界结果/错误摘要。 */
  "output"?: string;
};

export type Subtask = {
  "id": string;
  "name": string;
  "status": RunStatus;
  "detail": string;
};

export type AgentRun = {
  "id": string;
  "userName": string;
  "status": RunStatus;
  "model": string;
  "configVersion": string;
  "startedAt": string;
  "elapsedSeconds": number;
  /** 提供商实际报告的输入 token 数，未知为 null。 */
  "inputTokens": number | null;
  /** 提供商实际报告的输出 token 数，未知为 null。 */
  "outputTokens": number | null;
  /** 按已配置价格估算的美元金额；真实用量或价格不可用时为 null。 */
  "cost": number | null;
  "searchCount": number;
  "events": Array<RunEvent>;
  "subtasks": Array<Subtask>;
};

export type Source = {
  "id": string;
  "name": string;
  "kind": "rss";
  "sourceId": string;
  "url": string;
  /** 有效轮询周期，单位秒；界面可以换算为分钟显示。 */
  "interval": number;
  "status": "healthy" | "syncing" | "failed" | "disabled" | "unverified" | "invalid" | "stopping";
  /** RFC 3339 UTC 时间；原型未知/尚未发生时为空串。不得将空值显示为成功。 */
  "lastSuccess": ((string) | (""));
  /** RFC 3339 UTC 时间；原型未知/尚未发生时为空串。不得将空值显示为成功。 */
  "nextFetch": ((string) | (""));
  /** RFC 3339 UTC 时间；原型未知/尚未发生时为空串。不得将空值显示为成功。 */
  "lastChanged": ((string) | (""));
  "items": number;
  "error": string;
  /** 当前有效不可变快照 ID；无有效快照为 null。失败或304保留原值。 */
  "snapshotId": string | null;
  /** 当前快照原始数据实际取得时刻；304或失败不能更新成新的内容采集时间。 */
  "snapshotFetchedAt": string | null;
  /** 最近一次实际HTTP采集尝试时刻（含失败/304），不代表发布成功。 */
  "lastFetchedAt": string | null;
  /** 当前时间减snapshotFetchedAt；无有效快照为null。 */
  "cacheAgeSeconds": number | null;
  /** 无快照或缓存超过有效周期时为true；响应为304可延期有效性但不伪造快照年龄。 */
  "stale": boolean;
  "enabled"?: boolean;
  "health"?: "healthy" | "failed" | "invalid" | "unverified";
  "failureCount"?: number;
  "collectionStatus"?: "idle" | "queued" | "running" | "stopping" | "stopped";
  /** 可编辑配置版本，采集状态变化不递增。 */
  "version"?: number;
};

export type Delivery = {
  "id": string;
  "briefId": string;
  "userName": string;
  /** 站内简报位置，不包含邮件地址。 */
  "destination": string;
  "channel": "in_app";
  "status": DeliveryStatus;
  "attempts": number;
  "time": string;
  "error": string;
};

export type Session = {
  "kind": "anonymous";
  "userId": string;
  "name": string;
  "onboardingCompleted": boolean;
};

export type Error = {
  "code": "VALIDATION_ERROR" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "VERSION_CONFLICT" | "INVALID_STATE" | "SECRET_REQUIRED" | "SOURCE_INTERVAL_TOO_SHORT" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR" | "ACCOUNT_BLOCKED" | "CSRF_REJECTED";
  "message": string;
  "requestId": string;
  "fields"?: {
    [key: string]: string;
  };
};

export type SourceWrite = {
  "name": string;
  "kind": "rss";
  "sourceId": string;
  "url": string;
  /** 有效轮询周期，单位秒。 */
  "interval": number;
};

export type DeliverySettingsWrite = {
  /** 每日站内自动推送时间，按系统时区 Asia/Shanghai 解释。 */
  "time": string;
};

export type EnabledWrite = {
  "enabled": boolean;
};

export type GenerateBriefRequest = {
  "preferenceVersion": number;
};

export type HealthSummary = {
  "activeRuns": number;
  "failedSources": number;
  "failedDeliveries": number;
  "sampleCount": number;
  "completionRate": number | null;
  "generatedAt": string;
};

export type BriefPage = {
  "items": Array<Brief>;
  "nextCursor": string | null;
};

export type AgentRunPage = {
  "items": Array<AgentRun>;
  "nextCursor": string | null;
};

export type SourcePage = {
  "items": Array<Source>;
  "total": number;
  "page": number;
  "pageSize": 10;
  "totalPages": number;
  "invalidTotal": number;
};

export type DeliveryPage = {
  "items": Array<Delivery>;
  "nextCursor": string | null;
};

export type PreferencesWrite = ({
  /** 服务端版本，0 表示尚未配置；提交时原样回传作并发校验，成功保存由服务端递增。 */
  "version": number;
  /** 关注背景/职业说明，并非鉴权角色。 */
  "role": string;
  "topics": Array<string>;
  "keywords": Array<string>;
}) & (({
  "topics"?: unknown;
  [key: string]: unknown;
}) | ({
  "keywords"?: unknown;
  [key: string]: unknown;
}));

export type AdminSession = {
  "kind": "admin";
  "userId": string;
  "name": string;
};

export type AdminLoginRequest = {
  "email": string;
  "password": string;
};

export type GenerationProgress = {
  "id": string;
  "status": RunStatus;
  /** 兼容旧客户端的内部进度值；新版用户端不展示百分比。 */
  "percent": number | null;
  /** 兼容旧客户端的估计值；新版用户端不展示剩余时间。 */
  "remainingSeconds": number | null;
  "updatedAt": string;
  "briefId": string | null;
  /** 简短用户反馈，不含内部异常或诊断说明。 */
  "error": string;
  /** 真实业务阶段；终态为null，不根据工具次数或经过时间推算。 */
  "phase": "preparing" | "researching" | "publishing" | null;
  "phaseStartedAt": string | null;
  /** 正常完成但没有相关新闻；没有创建空简报，保留原简报。 */
  "emptyResult": boolean;
};

export type AnonymousAccount = {
  "id": string;
  "name": string;
  "createdAt": string;
  "lastSeenAt": string;
  "status": "active" | "blocked";
  "risk": "normal" | "watch" | "high";
  "requestsLastMinute": number;
  "generationsToday": number;
  "rateLimitHits": number;
  "activeGenerations": number;
  /** 脱敏来源标签，不返回原始IP或会话token。 */
  "ipLabel": string;
  "blockReason": string;
};

export type AbuseEvent = {
  "id": string;
  "accountId": string;
  "time": string;
  "kind": "rate_limited" | "account_blocked" | "account_unblocked" | "generation_rejected";
  "detail": string;
};

export type AnonymousPolicy = {
  "requestsPerMinute": number;
  "generationsPerDay": number;
  "maxConcurrentGenerations": number;
  "accountsPerIpHour": number;
};

export type AnonymousAccountStatusWrite = {
  "status": "active" | "blocked";
  "reason": string;
};

export type AnonymousAccountPage = {
  "items": Array<AnonymousAccount>;
  "nextCursor": string | null;
};

export type AbuseEventPage = {
  "items": Array<AbuseEvent>;
  "nextCursor": string | null;
};

export type AdminBrief = {
  "id": string;
  "title": string;
  "date": string;
  "version": number;
  "summary": string;
  "items": Array<StoredNewsItem>;
  "generationStatus": RunStatus;
  "deliveryStatus": DeliveryStatus;
  "generatedAt": string;
  "runId": string;
  "preferenceSnapshot": Preferences;
  /** 未取得有效证据的来源名称；部分完成时向读者明确缺失。 */
  "missingSources": Array<string>;
};

export type StoredNewsItem = {
  "id": string;
  "title": string;
  "summary": string;
  "reason": string;
  "topic": string;
  "source": string;
  /** 保留历史证据的原始来源类型；当前订阅采集仅支持 RSS，联网补充搜索使用 search。 */
  "sourceType": "rss" | "newsnow" | "search";
  "publishedAt": string | null;
  "url": string;
  "citations": Array<Citation>;
  /** 实际采集或搜索取得证据的时刻；绝不能代替 publishedAt。 */
  "fetchedAt": string;
  /** 不可变来源或搜索证据快照的公开不透明标识，不是宿主路径或运行标识。 */
  "snapshotId": string;
};

export type SourceBatchWrite = {
  "action": "disable" | "delete";
  "ids": Array<string>;
};

export type SourceBatchResult = {
  "succeeded": Array<string>;
  "failed": Array<{
    "id": string;
    "code": string;
    "message": string;
  }>;
};

export type SourceUpdate = {
  "name": string;
  "kind": "rss";
  "sourceId": string;
  "url": string;
  /** 有效轮询周期，单位秒。 */
  "interval": number;
  "version": number;
};

export type SourceDeletionItem = {
  "id": string;
  "name": string;
  "status": "pending" | "running" | "deleted" | "skipped" | "failed" | "unprocessed";
  "code": string;
  "message": string;
};

export type SourceDeletionJob = {
  "id": string;
  "mode": "selected" | "invalid";
  "status": "queued" | "running" | "completed" | "failed";
  "total": number;
  "processed": number;
  "deleted": number;
  "skipped": number;
  "failed": number;
  "items": Array<SourceDeletionItem>;
  "error": string;
  "createdAt": string;
  "updatedAt": string;
};

export type CurrentSourceDeletion = {
  "job": ((SourceDeletionJob) | (null));
};

export type components = {
  schemas: {
    "RunStatus": RunStatus;
    "DeliveryStatus": DeliveryStatus;
    "Preferences": Preferences;
    "DeliverySettings": DeliverySettings;
    "Citation": Citation;
    "NewsItem": NewsItem;
    "Brief": Brief;
    "RunEvent": RunEvent;
    "Subtask": Subtask;
    "AgentRun": AgentRun;
    "Source": Source;
    "Delivery": Delivery;
    "Session": Session;
    "Error": Error;
    "SourceWrite": SourceWrite;
    "DeliverySettingsWrite": DeliverySettingsWrite;
    "EnabledWrite": EnabledWrite;
    "GenerateBriefRequest": GenerateBriefRequest;
    "HealthSummary": HealthSummary;
    "BriefPage": BriefPage;
    "AgentRunPage": AgentRunPage;
    "SourcePage": SourcePage;
    "DeliveryPage": DeliveryPage;
    "PreferencesWrite": PreferencesWrite;
    "AdminSession": AdminSession;
    "AdminLoginRequest": AdminLoginRequest;
    "GenerationProgress": GenerationProgress;
    "AnonymousAccount": AnonymousAccount;
    "AbuseEvent": AbuseEvent;
    "AnonymousPolicy": AnonymousPolicy;
    "AnonymousAccountStatusWrite": AnonymousAccountStatusWrite;
    "AnonymousAccountPage": AnonymousAccountPage;
    "AbuseEventPage": AbuseEventPage;
    "AdminBrief": AdminBrief;
    "StoredNewsItem": StoredNewsItem;
    "SourceBatchWrite": SourceBatchWrite;
    "SourceBatchResult": SourceBatchResult;
    "SourceUpdate": SourceUpdate;
    "SourceDeletionItem": SourceDeletionItem;
    "SourceDeletionJob": SourceDeletionJob;
    "CurrentSourceDeletion": CurrentSourceDeletion;
  };
};

export const contractSource = "backend/src/zhigenews/contracts/openapi.json";
export const contractSha256 = "49bc93aaca5623a0d5ea7a99349c1a2f41ac63b1210b1a33885bfaa677885c5c";
export const operationMetadata = {
  "getSession": {
    "method": "GET",
    "path": "/auth/session",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getPreferences": {
    "method": "GET",
    "path": "/me/preferences",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "savePreferences": {
    "method": "PUT",
    "path": "/me/preferences",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getDeliverySettings": {
    "method": "GET",
    "path": "/me/delivery-settings",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "saveDeliverySettings": {
    "method": "PUT",
    "path": "/me/delivery-settings",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listBriefs": {
    "method": "GET",
    "path": "/me/briefs",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit",
      "date",
      "topic",
      "status",
      "q"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "generateBrief": {
    "method": "POST",
    "path": "/me/briefs",
    "role": "authenticated",
    "idempotencyRequired": true,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "getBrief": {
    "method": "GET",
    "path": "/me/briefs/{id}",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listOwnDeliveries": {
    "method": "GET",
    "path": "/me/deliveries",
    "role": "authenticated",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "retryOwnDelivery": {
    "method": "POST",
    "path": "/me/deliveries/{id}/retry",
    "role": "authenticated",
    "idempotencyRequired": true,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "getOverview": {
    "method": "GET",
    "path": "/admin/overview",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listSources": {
    "method": "GET",
    "path": "/admin/sources",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "q",
      "kind",
      "page"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "createSource": {
    "method": "POST",
    "path": "/admin/sources",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      201
    ],
    "stream": false
  },
  "saveSource": {
    "method": "PUT",
    "path": "/admin/sources/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getSource": {
    "method": "GET",
    "path": "/admin/sources/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "setSourceEnabled": {
    "method": "PUT",
    "path": "/admin/sources/{id}/enabled",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "fetchSource": {
    "method": "POST",
    "path": "/admin/sources/{id}/fetch",
    "role": "admin",
    "idempotencyRequired": true,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "listAdminRuns": {
    "method": "GET",
    "path": "/admin/runs",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit",
      "status",
      "model",
      "from",
      "to"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getAdminRun": {
    "method": "GET",
    "path": "/admin/runs/{id}",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "cancelAdminRun": {
    "method": "POST",
    "path": "/admin/runs/{id}/cancel",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "listAdminDeliveries": {
    "method": "GET",
    "path": "/admin/deliveries",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "retryAdminDelivery": {
    "method": "POST",
    "path": "/admin/deliveries/{id}/retry",
    "role": "admin",
    "idempotencyRequired": true,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "adminRunEvents": {
    "method": "GET",
    "path": "/admin/runs/{id}/events",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": true
  },
  "ensureAnonymousSession": {
    "method": "POST",
    "path": "/auth/anonymous",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "adminLogin": {
    "method": "POST",
    "path": "/admin/auth/login",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getAdminSession": {
    "method": "GET",
    "path": "/admin/auth/session",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "adminLogout": {
    "method": "DELETE",
    "path": "/admin/auth/session",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      204
    ],
    "stream": false
  },
  "getGenerationProgress": {
    "method": "GET",
    "path": "/me/generations/{id}",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "cancelGeneration": {
    "method": "POST",
    "path": "/me/generations/{id}/cancel",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "listAnonymousAccounts": {
    "method": "GET",
    "path": "/admin/anonymous-accounts",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "setAnonymousAccountStatus": {
    "method": "PUT",
    "path": "/admin/anonymous-accounts/{id}/status",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "listAbuseEvents": {
    "method": "GET",
    "path": "/admin/abuse-events",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getAnonymousPolicy": {
    "method": "GET",
    "path": "/admin/anonymous-policy",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "saveAnonymousPolicy": {
    "method": "PUT",
    "path": "/admin/anonymous-policy",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "getCurrentGeneration": {
    "method": "GET",
    "path": "/me/generations/current",
    "role": null,
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "stopSource": {
    "method": "POST",
    "path": "/admin/sources/{id}/stop",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "batchSources": {
    "method": "POST",
    "path": "/admin/sources/batch",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": true,
    "successStatuses": [
      200
    ],
    "stream": false
  },
  "deleteInvalidSources": {
    "method": "DELETE",
    "path": "/admin/sources/invalid",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      202
    ],
    "stream": false
  },
  "currentSourceDeletion": {
    "method": "GET",
    "path": "/admin/source-deletions/current",
    "role": "admin",
    "idempotencyRequired": false,
    "pathParameters": [],
    "queryParameters": [],
    "bodyRequired": false,
    "successStatuses": [
      200
    ],
    "stream": false
  }
} as const;
export type OperationId = keyof typeof operationMetadata;
export type OperationRequests = {
  "getSession": undefined;
  "getPreferences": undefined;
  "savePreferences": PreferencesWrite;
  "getDeliverySettings": undefined;
  "saveDeliverySettings": DeliverySettingsWrite;
  "listBriefs": undefined;
  "generateBrief": GenerateBriefRequest;
  "getBrief": undefined;
  "listOwnDeliveries": undefined;
  "retryOwnDelivery": undefined;
  "getOverview": undefined;
  "listSources": undefined;
  "createSource": SourceWrite;
  "saveSource": SourceUpdate;
  "getSource": undefined;
  "setSourceEnabled": EnabledWrite;
  "fetchSource": undefined;
  "listAdminRuns": undefined;
  "getAdminRun": undefined;
  "cancelAdminRun": undefined;
  "listAdminDeliveries": undefined;
  "retryAdminDelivery": undefined;
  "adminRunEvents": undefined;
  "ensureAnonymousSession": undefined;
  "adminLogin": AdminLoginRequest;
  "getAdminSession": undefined;
  "adminLogout": undefined;
  "getGenerationProgress": undefined;
  "cancelGeneration": undefined;
  "listAnonymousAccounts": undefined;
  "setAnonymousAccountStatus": AnonymousAccountStatusWrite;
  "listAbuseEvents": undefined;
  "getAnonymousPolicy": undefined;
  "saveAnonymousPolicy": AnonymousPolicy;
  "getCurrentGeneration": undefined;
  "stopSource": undefined;
  "batchSources": SourceBatchWrite;
  "deleteInvalidSources": undefined;
  "currentSourceDeletion": undefined;
};
export type OperationResponses = {
  "getSession": Session;
  "getPreferences": Preferences;
  "savePreferences": Preferences;
  "getDeliverySettings": DeliverySettings;
  "saveDeliverySettings": DeliverySettings;
  "listBriefs": BriefPage;
  "generateBrief": GenerationProgress;
  "getBrief": Brief;
  "listOwnDeliveries": DeliveryPage;
  "retryOwnDelivery": Delivery;
  "getOverview": HealthSummary;
  "listSources": SourcePage;
  "createSource": Source;
  "saveSource": Source;
  "getSource": Source;
  "setSourceEnabled": Source;
  "fetchSource": Source;
  "listAdminRuns": AgentRunPage;
  "getAdminRun": AgentRun;
  "cancelAdminRun": AgentRun;
  "listAdminDeliveries": DeliveryPage;
  "retryAdminDelivery": Delivery;
  "adminRunEvents": RunEvent;
  "ensureAnonymousSession": Session;
  "adminLogin": AdminSession;
  "getAdminSession": AdminSession;
  "adminLogout": undefined;
  "getGenerationProgress": GenerationProgress;
  "cancelGeneration": GenerationProgress;
  "listAnonymousAccounts": AnonymousAccountPage;
  "setAnonymousAccountStatus": AnonymousAccount;
  "listAbuseEvents": AbuseEventPage;
  "getAnonymousPolicy": AnonymousPolicy;
  "saveAnonymousPolicy": AnonymousPolicy;
  "getCurrentGeneration": ((GenerationProgress) | (null));
  "stopSource": Source;
  "batchSources": ((SourceBatchResult) | (SourceDeletionJob));
  "deleteInvalidSources": SourceDeletionJob;
  "currentSourceDeletion": CurrentSourceDeletion;
};
